<main>
    <section class="why-us">
        <div class="why-us__header">
            <h3>WHY US?</h3>
        </div>
        <div class="why-us__container">
            <div class="whys-us__img">
                <div class="whys-us__img--img">
                    <img src="<?php echo $_params['ruta_img']?>why1.jpg" alt="">
                </div>
                <div class="whys-us__img--img">
                    <img src="<?php echo $_params['ruta_img']?>why2.jpg" alt="">
                </div>
                <div class="whys-us__img--img">
                    <img src="<?php echo $_params['ruta_img']?>why3.jpg" alt="">
                </div>

            </div>
            
            <div class="container__why">

                <?=($this->data['texto']) ? $this->data['texto'] : ''?>
                
                <!-- <p><strong>
                    OUR UNIQUE VALUE PROPOSITION IS SIMPLE:<br>
                    We are the low-cost, pragmatic and customized separation and divorce solution for priceless peace of mind.</strong>
                </p>

                <p>
                    As an experienced family law attorney helping couples navigate all types of divorce proceedings, Founder Aliette Carolan recognized an opportunity to give couples what they really want: the ability to easily create their own legal documents and finalize their separations, custody arrangements, and divorces.
                </p>

                <p>
                    Ms. Carolan, a divorced parent and noted author on family friendly divorce, recognized that the generic forms which are provided to the public by the state of Florida and widely available across the internet lacked important details such as contingency plans for time-sharing of children. Applying her legal acumen and extensive experience, she customized the forms to include all the necessary items, such as the necessary waivers and protection against the other party’s debts. These cost-efficient solutions, which were developed in response to the emerging divorce trends resulting from the pandemic, are particularly relevant today as the divorce rate is at an all-time high and family finances are at an all-time low. These trends, which are expected to continue in the foreseeable future, helped shape the unique offerings and price point which only TheQuickDivorce.com provides.
                </p>

                <p>
                    Ms. Carolan’s personal passion for redefining the divorce process is evidenced not only by the quality of the innovative solution she created, but most significantly by her commitment to roll up her sleeves and share her knowledge through her writing, speaking engagements, media coverage, and social media channels.
                </p> -->

            </div>
        </div>
    </section>
</main>