<script src="http://cdn.ckeditor.com/4.5.11/standard-all/ckeditor.js"></script>
<script>

$(document).ready(function() {
	
			
	$('#cargar_trabajo').submit(function(){
			
			
			
			/*if ($("#fecha").val() == "") {
				alert("Debe completar el campo fecha");
				//$("#titulo").val('');
				$('#fecha').focus();			
				//$("#titulo").attr('placeholder', 'Titulo');
				return false;        
			}*/
			
			if ($("#precio").val() == "") {
				alert("Debe completar el campo precio");
				//$("#titulo").val('');
				$('#precio').focus();			
				//$("#titulo").attr('placeholder', 'Titulo');
				return false;        
			}
			
			if ($("#sku").val() == "") {
				alert("Debe completar el campo numero de sku");
				//$("#titulo").val('');
				$('#sku').focus();			
				//$("#titulo").attr('placeholder', 'Titulo');
				return false;        
			}
			if ($("#titulo").val() == "") {
				alert("Debe completar el campo titulo");
				//$("#titulo").val('');
				$('#titulo').focus();			
				//$("#titulo").attr('placeholder', 'Titulo');
				return false;        
			}
			
			if ($("#ancho").val() == "") {
				alert("Debe completar el campo ancho rueda");
				//$("#titulo").val('');
				$('#ancho').focus();			
				//$("#titulo").attr('placeholder', 'Titulo');
				return false;        
			}
			
			if ($("#perfil").val() == "") {
				alert("Debe completar el campo perfil rueda");
				//$("#titulo").val('');
				$('#perfil').focus();			
				//$("#titulo").attr('placeholder', 'Titulo');
				return false;        
			}
			
			if ($("#rodado").val() == "") {
				alert("Debe completar el campo rodado");
				//$("#titulo").val('');
				$('#rodado').focus();			
				//$("#titulo").attr('placeholder', 'Titulo');
				return false;        
			}
			
			/*if ($("#diametro").val() == "") {
				alert("Debe completar el campo diametro rueda");
				//$("#titulo").val('');
				$('#diametro').focus();			
				//$("#titulo").attr('placeholder', 'Titulo');
				return false;        
			}
			
			if ($("#serie").val() == "") {
				alert("Debe completar el campo serie");
				//$("#titulo").val('');
				$('#serie').focus();			
				//$("#titulo").attr('placeholder', 'Titulo');
				return false;        
			}
			
			if ($("#ic").val() == "") {
				alert("Debe completar el campo I.C.");
				//$("#titulo").val('');
				$('#ic').focus();			
				//$("#titulo").attr('placeholder', 'Titulo');
				return false;        
			}
			
			if ($("#iv").val() == "") {
				alert("Debe completar el campo I.V.");
				//$("#titulo").val('');
				$('#iv').focus();			
				//$("#titulo").attr('placeholder', 'Titulo');
				return false;        
			}*/			
			
			titulo_desc = CKEDITOR.instances.desc.getData();
			if (titulo_desc===''){
				alert("Debe completar el campo descripcion");
				CKEDITOR.instances.desc.focus();	
				return false;    
			}
			
			titulo_beneficios = CKEDITOR.instances.beneficios.getData();
			if (titulo_beneficios===''){
				alert("Debe completar el campo beneficios");
				CKEDITOR.instances.beneficios.focus();	
				return false;    
			}
			
			titulo_datos_tecnicos = CKEDITOR.instances.datos_tecnicos.getData();
			if (titulo_datos_tecnicos===''){
				alert("Debe completar el campo datos tecnicos");
				CKEDITOR.instances.datos_tecnicos.focus();	
				return false;    
			}
						
			
			/*if ($("#imagen").val() == "") {
				alert("Debe subir una imagen");
				$('#imagen').focus();			
				return false;        
			}*/
			
			
			return true;
		
	
	});
	
	
	
});
</script>
<div class="row">
  	<div class="col-lg-12">
    	
        <div class="row">
        
        	<form class="form-horizontal" id="cargar_trabajo" action="" method="POST" role="form" enctype="multipart/form-data">
            <input type="hidden" name="envio01" value="1" />
            
            <fieldset>
    			<legend>Cargar Producto</legend>           	
                
                
                <!--<div class="form-group formulario_back">
              		<label for="fecha" class="col-lg-2 control-label">Fecha</label>
                  	<div class="col-lg-10">
                        <input type="text" class="form-control" id="fecha" name="fecha" placeholder="Fecha" >
                        <input type="hidden" name="hora" id="hora" >
                   	</div>
           		</div>-->
                
                <div class="form-group formulario_back">
              		<label for="num_referencia" class="col-lg-2 control-label">Estado</label>
                  	<div class="col-lg-10">
                    	<select class="form-control" name="estado">
                        	<option value="1">Alta</option>
                            <option value="2">Baja</option>
                        </select>
                   	</div>
           		</div>
                
                <div class="form-group formulario_back">
              		<label for="categoria" class="col-lg-2 control-label">Categorias</label>
                  	<div class="col-lg-10">
                    	<select class="form-control" name="categoria" id="categoria">
                        	<?php foreach($this->cat as $cat):?>
                            <option value="<?=$cat->id?>"><?=$cat->nombre?></option>
                            <?php endforeach?>
                        </select>
                   	</div>
           		</div>
                
                <div class="form-group formulario_back">
              		<label for="stock" class="col-lg-2 control-label">Stock</label>
                  	<div class="col-lg-10">
                    	<select class="form-control" name="stock" id="stock">
                        	<option value="1">Si</option>
                            <option value="0">No</option>
                        </select>
                   	</div>
           		</div>
                
                <hr />
                
                
                <div class="form-group formulario_back">
              		<label for="precio" class="col-lg-2 control-label">Precio</label>
					<div class="col-lg-10 input-group"> 
                      <div class="input-group-addon">$</div>
                      <input class="form-control" id="precio" name="precio" placeholder="Precio" type="text" value="<?php if(isset($this->data['precio'])) echo $this->data['precio']?>" />                        
                   	</div>
           		</div>
                
                <div class="form-group formulario_back">
              		<label for="num_referencia" class="col-lg-2 control-label">N&uacute;mero SKU</label>
                  	<div class="col-lg-10">
                    	<input class="form-control" id="sku" name="sku" placeholder="N&uacute;mero SKU" type="text" value="<?php if(isset($this->data['sku'])) echo $this->data['sku']?>" />
                   	</div>
           		</div>
                
                <div class="form-group formulario_back">
              		<label for="nombre" class="col-lg-2 control-label">T&iacute;tulo</label>
                  	<div class="col-lg-10">
                    	<input class="form-control" id="titulo" name="titulo" placeholder="T&iacute;tulo" type="text" value="<?php if(isset($this->data['titulo'])) echo $this->data['titulo']?>" />
                   	</div>
           		</div>
                
                 <div class="form-group formulario_back">
              		<label for="ancho" class="col-lg-2 control-label">Ancho Rueda</label>
                  	<div class="col-lg-10">
                    	<input class="form-control" id="ancho" name="ancho" placeholder="Ancho Rueda" type="text" value="<?php if(isset($this->data['ancho'])) echo $this->data['ancho']?>" />
                   	</div>
           		</div>
                
                 <div class="form-group formulario_back">
              		<label for="perfil" class="col-lg-2 control-label">Perfil Rueda</label>
                  	<div class="col-lg-10">
                    	<input class="form-control" id="" name="perfil" placeholder="Perfil Rueda" type="text" value="<?php if(isset($this->data['perfil'])) echo $this->data['perfil']?>" />
                   	</div>
           		</div>
                
                 <div class="form-group formulario_back">
              		<label for="rodado" class="col-lg-2 control-label">Rodado</label>
                  	<div class="col-lg-10">
                    	<input class="form-control" id="rodado" name="rodado" placeholder="Rodado" type="text" value="<?php if(isset($this->data['rodado'])) echo $this->data['rodado']?>" />
                   	</div>
           		</div>
                
               <!-- 
               <div class="form-group formulario_back">
              		<label for="diametro" class="col-lg-2 control-label">Di&aacute;metro Rueda</label>
                  	<div class="col-lg-10">
                    	<input class="form-control" id="diametro" name="diametro" placeholder="Di&aacute;metro Rueda" type="text" value="<?php if(isset($this->data['diametro'])) echo $this->data['diametro']?>" />
                   	</div>
           		</div>
                
                 <div class="form-group formulario_back">
              		<label for="serie" class="col-lg-2 control-label">Serie</label>
                  	<div class="col-lg-10">
                    	<input class="form-control" id="serie" name="serie" placeholder="Serie" type="text" value="<?php if(isset($this->data['serie'])) echo $this->data['serie']?>" />
                   	</div>
           		</div>
                
                 <div class="form-group formulario_back">
              		<label for="ic" class="col-lg-2 control-label">I.C.</label>
                  	<div class="col-lg-10">
                    	<input class="form-control" id="ic" name="ic" placeholder="I.C." type="text" value="<?php if(isset($this->data['ic'])) echo $this->data['ic']?>" />
                   	</div>
           		</div>
                
                 <div class="form-group formulario_back">
              		<label for="iv" class="col-lg-2 control-label">I.V.</label>
                  	<div class="col-lg-10">
                    	<input class="form-control" id="iv" name="iv" placeholder="I.V." type="text" value="<?php if(isset($this->data['iv'])) echo $this->data['iv']?>" />
                   	</div>
           		</div>
                -->
                
                             
               
                 <div class="form-group formulario_back">
                    <label for="desc" class="col-lg-2 control-label">Descripci&oacute;n</label>
                    <div class="col-lg-10">
                    	<textarea class="form-control" id="desc" name="desc"><?php if(isset($this->data['descripcion'])) echo $this->data['descripcion']?></textarea>
						 <script>
                            CKEDITOR.replace('desc', {
                                extraPlugins: 'colorbutton'
                            });
                        </script>
                    	
                       
                    </div>
                </div>
                              
                
                <div class="form-group formulario_back">
                    <label for="desc" class="col-lg-2 control-label">Beneficios</label>
                    <div class="col-lg-10">
                    	<textarea class="form-control" id="beneficios" name="beneficios"><?php if(isset($this->data['beneficios'])) echo $this->data['beneficios']?></textarea>
						 <script>
                            CKEDITOR.replace('beneficios', {
                                extraPlugins: 'colorbutton'
                            });
                        </script>
                    </div>
                </div>
                
                <div class="form-group formulario_back">
                    <label for="desc" class="col-lg-2 control-label">Datos Tecnicos</label>
                    <div class="col-lg-10">
                    	<textarea class="form-control" id="datos_tecnicos" name="datos_tecnicos"><?php if(isset($this->data['datos_tecnicos'])) echo $this->data['datos_tecnicos']?></textarea>
						 <script>
                            CKEDITOR.replace('datos_tecnicos', {
                                extraPlugins: 'colorbutton'
                            });
                        </script>
                    	
                       
                    </div>
                </div>
                
                
                 <div class="form-group formulario_back">
                 <label for="contenido" class="col-lg-2 control-label">Galeria de Im&aacute;genes</label>
                  	<div class="col-lg-10">
                        <div class="col-lg-5">
                            <button type="button" class="btn btn-info" data-toggle="modal" data-target="#_car_imgg_gal">
                                Cargar Im&aacute;genes
                            </button>
                        </div>
                        <div class="col-lg-7">
                            <div class="list-group aa conexion _load_img_final_gal" id="bloque_imgs_usuario">
                            <?php $_img = admin::traerImgGal($this->_sess->get('carga_actual'),'productos','galeria');?>
                            <?php if($_img !=''):?>
                            <?php foreach($_img as $m):?>
                            <div><img src=" <?= $this->_conf['base_url'] . "public/img/subidas/productos/galeria/thumb/" . $m->path ?>"  class="img-thumbnail"></div>
                            <?php endforeach?>
                            <?php endif?>                           
                            </div>
                        </div>
                    </div>
                </div>
                
                
                  
                <div class="form-group formulario_back">
              		<label for="contenido" class="col-lg-2 control-label">Imagen medidas</label>
                  	<div class="col-lg-10">
                        <div class="col-lg-5">
                            <button type="button" class="btn btn-info" data-toggle="modal" data-target="#_car_imgg_medidas">
                                Cargar Imagen
                            </button>
                        </div>
                        <div class="col-lg-7">
                        	<div class="list-group aa conexion _load_img_final_medidas" id="bloque_imgs_usuario">
							<?php $_img = admin::traerImg($this->_sess->get('carga_actual'),'productos','medidas');?>
							<?php if($_img !=''):?>
                            <div><img src=" <?= $this->_conf['base_url'] . "public/img/subidas/productos/medidas/thumb/" . $_img->path ?>"  class="img-thumbnail"></div>
                            <?php endif?>
                            </div>
                        </div>
                   	</div>                    
           		</div> 
                
            	<div class="form-group formulario_back">
              		<label for="contenido" class="col-lg-2 control-label">Imagen beneficios</label>
                  	<div class="col-lg-10">
                        <div class="col-lg-5">
                            <button type="button" class="btn btn-info" data-toggle="modal" data-target="#_car_imgg_beneficios">
                                Cargar Imagen
                            </button>
                        </div>
                        <div class="col-lg-7">
                        	<div class="list-group aa conexion _load_img_final_beneficios" id="bloque_imgs_usuario">
							<?php $_img = admin::traerImg($this->_sess->get('carga_actual'),'productos','beneficios');?>
							<?php if($_img !=''):?>
                            <div><img src=" <?= $this->_conf['base_url'] . "public/img/subidas/productos/beneficios/thumb/" . $_img->path ?>"  class="img-thumbnail"></div>
                            <?php endif?>
                            </div>
                        </div>
                   	</div>                    
           		</div>
                   
                
                <div class="form-group">
                    <div class="col-lg-12">
                        <input type="submit" class="btn btn-primary btn-lg btn-block" id="validatex" name="cargar" value="Cargar" />
                    </div>
                </div>
		</fieldset>
	</form>
	</div>
    
	<br><br>
        
    </div>
    
</div>

<div class="modal inmodal fade" id="_car_imgg_gal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
                <i class="fa fa-laptop modal-icon"></i>
                <h4 class="modal-title">Cargar Im&aacute;genes</h4>
            </div>
            <div class="modal-body">
			<script>
					Dropzone.options.myAwesomeDropzone = {
						autoProcessQueue: false,
						paramName: 'file',
						parallelUploads: 10,
						maxFiles: 50,
						maxFilesize: 15, //MB
						dictDefaultMessage: 'Arrastre aqui para cargar, o click para seleccionar',
						acceptedFiles: 'image/*',
				   
						init: function() {
			
							var myDropzone = this;
			
							myDropzone.on("addedfile", function(file) {
								file.previewElement.addEventListener("click", function() { myDropzone.removeFile(file);});
							});
			
							this.element.querySelector("button[type=submit]").addEventListener("click", function(e) {
								e.preventDefault();
								e.stopPropagation();                                
								
								/*if ($("#imagen_principal_nombre").val() == "") {
									alert("Debe completar el campo Nombre");
									$("#imagen_principal_nombre").val('');
									$('#imagen_principal_nombre').focus();            
									return false;        
								}
								
								if ($("#imagen_principal_nombre").val().length < 4) {
									alert("El campo Nombre debe tener un mínimo de 4 caracteres");
									$("#imagen_principal_nombre").val('');
									$('#imagen_principal_nombre').focus();            
									return false;        
								}*/
								myDropzone.processQueue();
							});
			
							/*this.on('thumbnail', function(file) {
							
							});*/
							
							/*this.on("queuecomplete", function(file) {img_final_gal('productos','galeria');});
							this.on("maxfilesexceeded", function(file){this.removeFile(file);});
							this.on("error", function(file) {alert(file)});
							this.on("complete", function(file) {this.removeAllFiles(file);});*/
							
							this.on("queuecomplete", function(file) { this.removeAllFiles(file);img_final_gal('cargar','productos','galeria');});
							this.on("maxfilesexceeded", function(file) { this.removeFile(file); });
							this.on("error", function(file) { alert("Error!"); });
							
							
						}
					};
               
               				
											
				
                function img_final_gal(_accion, _tipo, _pos){
                    var url= _root_ + "administrador/imagenes/traerImagenesGalerias/"+_accion+"/"+_tipo+"/"+_pos;
                    $.ajax({
                        url:url,
                        contentType:"application/x-www-form-urlencoded",
                        dataType:"html",
                        error:function(){
                            //$("._load_img_final_logo").html("La conexion se ha perdido. <a href='" + _root_ + "administrador/imagenes'>Reinicie el proceso.</a>");
                        },
            
                        ifModified:false,
                        processData:true,
                        success:function(datas){
                            $("._load_img_final_gal").append(datas).fadeIn("slow");
							$('#_car_imgg_gal').modal('hide');
                        },
                        type:"POST"
                    });
                }
				
                </script>
                <div class="loader"></div>
                <div id="contenedor">
            
                    <form class="form-inline dropzone" id="my-awesome-dropzone" action="<?=$this->_conf['base_url']?>administrador/imagenes/cargImgLote/productos/galeria">
                        <input type="hidden" name="envio_img_princip" value="1">
                        <!--<div class="form-group">
                            <label for="Nombre">
                                <small>Nombre</small>&nbsp;
                            </label>
                            <input type="text" class="form-control input-sm" id="imagen_principal_nombre" name="imagen_principal_nombre" placeholder="Nombre" maxlength="50">
                        </div>-->
                                                        
                        <div class="dropzone-previews"></div>
                        <button type="submit" class="btn btn-primary pull-right">Cargar</button>
                    </form>
                    <p class="eliminarThumb">Hace click sobre la miniatura para eliminarla.</p>
                    
                     <hr> 
                     
                    <div class="row">
                        <div class="col-lg-12">
                            <p class="text-danger"> 
                                <small>Peso m&aacute;ximo imagen: <strong>15 Mb.</strong></small>        
                            </p>
                        </div>
                    </div>
                   
                                      
                </div>
        	</div>  
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Cerrar</button>
            </div>        
    	</div>
    </div>
</div>

<div class="modal inmodal fade" id="_car_imgg_medidas" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
                <i class="fa fa-laptop modal-icon"></i>
                <h4 class="modal-title">Cargar Imagen</h4>
            </div>
            <div class="modal-body">
			<script>
					Dropzone.options.myAwesomeDropzoneMedidas = {
						autoProcessQueue: false,
						paramName: 'file',
						parallelUploads: 1,
						maxFiles: 1,
						maxFilesize: 15, //MB
						dictDefaultMessage: 'Arrastre aqui para cargar, o click para seleccionar',
						acceptedFiles: 'image/*',
				   
						init: function() {
			
							var myDropzone = this;
			
							myDropzone.on("addedfile", function(file) {
								file.previewElement.addEventListener("click", function() { myDropzone.removeFile(file);});
							});
			
							this.element.querySelector("button[type=submit]").addEventListener("click", function(e) {
								e.preventDefault();
								e.stopPropagation();                                
								myDropzone.processQueue();
							});
			
							/*this.on('thumbnail', function(file) {
							
							});*/
							
							this.on("queuecomplete", function(file) {this.removeAllFiles(file);img_final_medidas('cargar','productos','medidas');});
							this.on("maxfilesexceeded", function(file){this.removeFile(file);});
							this.on("error", function(file) {alert(file)});
							//this.on("complete", function(file) {this.removeAllFiles(file);});
						}
					};
               
               				
				
				
               /* function img_final(_seccion){
                    var url= _root_ + "administrador/imagenes/traerImagenfinal/"+_seccion;
                    $.ajax({
                        url:url,
                        contentType:"application/x-www-form-urlencoded",
                        dataType:"html",
                        error:function(){
                            $("._load_img_final").html("La conexion se ha perdido. <a href='" + _root_ + "administrador/imagenes'>Reinicie el proceso.</a>");
                        },
            
                        ifModified:false,
                        processData:true,
                        success:function(datas){
                            $("._load_img_final").html(datas).fadeIn("slow");
                           // $("#_car_imgg .ambito_recorte").html('');
							//$(".finalizar_proceso").show();
							$('#_car_imgg').modal('hide');
                        },
                        type:"POST",
                        timeout:3000
                    });
                }*/
				
				 function img_final_medidas(_accion, _tipo, _pos){
                    var url= _root_ + "administrador/imagenes/traerImagenfinal/"+_accion+"/"+_tipo+"/"+_pos;
                    $.ajax({
                        url:url,
                        contentType:"application/x-www-form-urlencoded",
                        dataType:"html",
                        error:function(){
                            //$("._load_img_final_logo").html("La conexion se ha perdido. <a href='" + _root_ + "administrador/imagenes'>Reinicie el proceso.</a>");
                        },
            
                        ifModified:false,
                        processData:true,
                        success:function(datas){
                            $("._load_img_final_medidas").html(datas).fadeIn("slow");
							$('#_car_imgg_medidas').modal('hide');
                        },
                        type:"POST"
                    });
                }
				
				
                </script>
                <div class="loader"></div>
                <div id="contenedor">
            
                    <form class="form-inline dropzone" id="my-awesome-dropzone-medidas" action="<?=$this->_conf['base_url']?>administrador/imagenes/cargImg/productos/medidas">
                        <input type="hidden" name="envio_img_princip" value="1">
                        <div class="dropzone-previews"></div>
                        <button type="submit" class="btn btn-primary pull-right">Cargar</button>
                    </form>
                    <p class="eliminarThumb">Hace click sobre la miniatura para eliminarla.</p>
                    
                     <hr> 
                     
                    <div class="row">
                        <div class="col-lg-12">
                            <p class="text-danger"> 
                                <small>Peso m&aacute;ximo imagen: <strong>15 Mb.</strong></small>        
                            </p>
                        </div>
                    </div>
                    
                  
                    
                </div>
        	</div>  
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Cerrar</button>
            </div>        
    	</div>
    </div>
</div>

<div class="modal inmodal fade" id="_car_imgg_beneficios" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
                <i class="fa fa-laptop modal-icon"></i>
                <h4 class="modal-title">Cargar Imagen</h4>
            </div>
            <div class="modal-body">
			<script>
					Dropzone.options.myAwesomeDropzoneBeneficios = {
						autoProcessQueue: false,
						paramName: 'file',
						parallelUploads: 1,
						maxFiles: 1,
						maxFilesize: 15, //MB
						dictDefaultMessage: 'Arrastre aqui para cargar, o click para seleccionar',
						acceptedFiles: 'image/*',
				   
						init: function() {
			
							var myDropzone = this;
			
							myDropzone.on("addedfile", function(file) {
								file.previewElement.addEventListener("click", function() { myDropzone.removeFile(file);});
							});
			
							this.element.querySelector("button[type=submit]").addEventListener("click", function(e) {
								e.preventDefault();
								e.stopPropagation();                                
								myDropzone.processQueue();
							});
			
							/*this.on('thumbnail', function(file) {
							
							});*/
							
							this.on("queuecomplete", function(file) {this.removeAllFiles(file);img_final_beneficios('cargar','productos','beneficios');});
							this.on("maxfilesexceeded", function(file){this.removeFile(file);});
							this.on("error", function(file) {alert(file)});
							//this.on("complete", function(file) {this.removeAllFiles(file);});
						}
					};
               
               				
				
				
				
				 function img_final_beneficios(_accion, _tipo, _pos){
                    var url= _root_ + "administrador/imagenes/traerImagenfinal/"+_accion+"/"+_tipo+"/"+_pos;
                    $.ajax({
                        url:url,
                        contentType:"application/x-www-form-urlencoded",
                        dataType:"html",
                        error:function(){
                            //$("._load_img_final_logo").html("La conexion se ha perdido. <a href='" + _root_ + "administrador/imagenes'>Reinicie el proceso.</a>");
                        },
            
                        ifModified:false,
                        processData:true,
                        success:function(datas){
                            $("._load_img_final_beneficios").html(datas).fadeIn("slow");
							$('#_car_imgg_beneficios').modal('hide');
                        },
                        type:"POST"
                    });
                }
				
				
                </script>
                <div class="loader"></div>
                <div id="contenedor">
            
                    <form class="form-inline dropzone" id="my-awesome-dropzone-beneficios" action="<?=$this->_conf['base_url']?>administrador/imagenes/cargImg/productos/beneficios">
                        <input type="hidden" name="envio_img_princip" value="1">
                        <div class="dropzone-previews"></div>
                        <button type="submit" class="btn btn-primary pull-right">Cargar</button>
                    </form>
                    <p class="eliminarThumb">Hace click sobre la miniatura para eliminarla.</p>
                    
                     <hr> 
                     
                    <div class="row">
                        <div class="col-lg-12">
                            <p class="text-danger"> 
                                <small>Peso m&aacute;ximo imagen: <strong>15 Mb.</strong></small>        
                            </p>
                        </div>
                    </div>
                    
                  
                    
                </div>
        	</div>  
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Cerrar</button>
            </div>        
    	</div>
    </div>
</div>