<main>
    <section class="introduction">
        <div class="slide-a">        
            <p class="legend">
                Your life is what you make of it <br/>
                and you can live the life of your wildest <br/>
                dreams if you take responsibility for it.<br>
                <span>— Aliette H. Carolan, Esq. | Family Law</span>
            </p>
        </div>
    </section>

    <section class="solution">
        <div class="container">
            <p class="tit--solution">
                <strong>YOUR SMART SOLUTION</strong>
                <br/>
                THE BEST WAY OUT AND FASTEST WAY FORWARD
            </p>

            <p>
                If you want to keep your money in the bank rather than spend it on divorce<br>
                lawyers, and if you want to enjoy your time in peace rather than waste it on<br>
                legal wrangles, then you’ve come to the right place.
            </p>

            <p>
                <strong>Welcome to TheQuickDivorce.com</strong>
                <br/>
                Your go-to online hub for a low-cost, efficient, hassle-free separation and divorce.<br>
                Created by an experienced family law attorney and divorced Mom, specifically for<br>
                couples who want the smartest – and quickest – way forward.
            </p>
        </div>
    </section>

    <section class="steps">
        <div class="border-line">
            <div class="container">
                <p class="steps__intro">
                    TheQuickDivorce.com is an online platform dedicated to minimizing the costs and maximizing the outcomes of separation and divorce in just 3 EASY STEPS! We enable our customers to create the customized legal documents they need, without having to hire costly lawyers or other professionals.
                </p>

                <div class="steps__by-steps">
                    <article class="steps__by-steps--step1">
                        <p>Find out if you qualify<br>
                            and purchase your package</p>
                            <span class="digit">1</span>
                    </article>
                    <article class="steps__by-steps--step2">
                        <p>Complete the intake form<br>
                            after checkout</p>
                            <span class="digit">2</span>
                    </article>
                    <article class="steps__by-steps--step3">
                        <p>Complete the form package<br>
                            via the link sent to your email.</p>
                            <span class="digit">3</span>
                    </article>
                </div>

                <a href="<?=$this->_conf['base_url']?>getstarted" class="button">
                    <p><strong>GET STARTED NOW</strong></p>
                </a>
            </div>
            
        </div>
    </section>

    <section class="why">
            <h2>Why TheQuickDivorce.com?</h2>

            <div class="porta__why">
                <div class="porta__why--img1">
                    <h3>AFFORDABLE<br>
                        AND EFFICIENT</h3>
                    <img src="<?php echo $_params['ruta_img']?>affordable.jpg" alt="affordable and efficcient">
                </div>

                <div class="porta__why--img2">
                    <h3>EFFECTIVE<br>
                        AND USER-FRIENDLY</h3>
                    <img src="<?php echo $_params['ruta_img']?>effective.jpg" alt="Effective and user-friendly">
                </div>

                <div class="porta__why--img3">
                    <h3>TRUSTED<br>
                        AND QUICK!</h3>
                    <img src="<?php echo $_params['ruta_img']?>trusted.jpg" alt="Trusted and Quick">
                </div>
            </div>
    </section>

    <!-- <section class="featured">
        <div class="container">
            <h3>WE HAVE BEEN FEATURED ON</h3>

            <div class="featured__brands">
                <img src="<?php echo $_params['ruta_img']?>featured-nyt.png" alt="the new york times">
                <img src="<?php echo $_params['ruta_img']?>featured-dbr.png" alt="daiily business review">
                <img src="<?php echo $_params['ruta_img']?>featured-nbc.png" alt="nbc news">
                <img src="<?php echo $_params['ruta_img']?>featured-medium.png" alt="medium">
            </div>

            <a href="<?=$this->_conf['base_url']?>press" class="button"><p><strong>READ MORE</strong></p></a>

        </div>
    </section> -->

    <section class="target">
        <div class="border-line">
            <div class="container">
                <h3>OUR MISSION</h3>
                <p>To provide the low-cost, do-it-yourself  separation<br>
                and divorce solutions couples need.</p>

                <h3>OUR VISION</h3>
                <p>To serve as the go-to online platform enabling couples to minimize the costs<br>
                    of separation and divorce and maximize their peace of mind.</p> 

                    <a href="<?=$this->_conf['base_url']?>getstarted" class="button"><p><strong>GET STARTED NOW</strong></p></a>
            </div>
        </div>
    </section>

    <section class="book">
        <div class="book__col">
            <img src="<?php echo $_params['ruta_img']?>book-white.jpg" alt="the positive divorce moment">
            <h4>WHITE PAPER</h4>
            <p>Aliette Carolan, a noted family
                law attorney and author on
                family friendly divorce, has
                published a new whitepaper
                with guidance on minimizing
                the headaches and maximizing
                the positive outcomes of
                divorce. Submit your contact
                details below to request a
                complimentary copy of her
                whitepaper.</p>

                <a href="<?=$this->_conf['base_url']?>whitepaper" class="button">
                    <p><strong>DOWNLOAD</strong></p>
                </a>
        </div>
        <div class="book__col"></div>
        <div class="book__col">
            <img src="<?php echo $_params['ruta_img']?>book-book.png" alt="just in case">
            <h4>BOOK</h4>
            <p>Just in Case!! The Smart
                Woman’s Guide to Marriage
                and Self-Sufficiency by Aliette
                Carolan. Establish your
                personal independence and
                financial solvency to be
                self-sufficient no matter what
                life throws at you. To learn
                more life tips and tactics, use
                the button below to purchase a
                copy of this book.</p>

                <a href="https://www.amazon.com/Just-Case-Lose-Your-Heart/dp/1899694730/ref=sr_1_1?dchild=1&keywords=aliette+carolan&qid=1602195470&s=books&sr=1-1" target="_blank" class="button">
                    <p><strong>PURCHASE</strong></p>
                </a>
        </div>
    </section>

    <section class="read-blog">
        <div class="container">

            <h3>READ OUR BLOG</h3>

            <div class="read-blog__row">

            	<?php if($this->blogs):?>
            	<?php foreach($this->blogs as $blogs):?>

                <article class="card">
                    <a href="<?=$this->_conf['base_url']?>blog/detail/<?=$blogs['item']?>" class="card__img">
                    	<?php $_img = admin::traerImg($blogs['identificador'],'blog');?>
                    	<?php if($_img):?>
                        <img src="<?= $this->_conf['base_url'] . "public/img/subidas/blog/thumb/" . $_img->path?>" alt="">
                        <?php endif?>
                    </a>
                    <div class="card__content">
                        <h3 class="card__content--tit">
                            <a href="<?=$this->_conf['base_url']?>blog/detail/<?=$blogs['item']?>">
                            	<?=$blogs['titulo']?>
                            </a>
                        </h3>
                        <p class="card__content--date"><?=date('F d, Y', strtotime($blogs['fecha']))?></p>
                        <p class="card__content--down">
                            <?=strip_tags(home::limitarTitulo($blogs['texto'], 15))?>
                        </p>
                        <a href="<?=$this->_conf['base_url']?>blog/detail/<?=$blogs['item']?>" class="card__content--more">READ MORE <span>&gt;</span></a>
                    </div>

                </article>

            	<?php endforeach?>
            	<?php endif?>

            </div>

            <a href="<?=$this->_conf['base_url']?>blog" class="button"><p><strong>MORE ARTICLES</strong></p></a>

        </div>
    </section>
</main>



