<style type="text/css">
.jcrop-holder #preview-pane {
  display: block;
  position: absolute;
  z-index: 2000;
  top: 0%;
  right: -18%;
  border: 5px #fff solid !important;
  -webkit-border-radius: 6px;
  -moz-border-radius: 6px;
  border-radius: 6px;
  -webkit-box-shadow: 1px 1px 5px 2px rgba(0, 0, 0, 0.2);
  -moz-box-shadow: 1px 1px 5px 2px rgba(0, 0, 0, 0.2);
  box-shadow: 1px 1px 5px 2px rgba(0, 0, 0, 0.2);
  cursor: move;
}
<?php 
$_an = admin::porcentajeXX(round($this->_conf['formatos_img'][$this->tipo]['ancho']/2),100,0);
$_al = admin::porcentajeXX(round($this->_conf['formatos_img'][$this->tipo]['alto']/2),100,0);
?>
#preview-pane{
    width: <?=$_an?>px;
    height: <?=$_al?>px;
    overflow: hidden;
}
.preview-container {
    width: <?=$_an?>px;
    height: <?=$_al?>px;
}
</style>

<script>   
$(function(){
  $("#btn_enviar").click(function(){
     
      $("#_load_xx").show();
      var url= _root_ + "administrador/imagenes/recortarimagennuevo/<?=$this->accion?>/<?=$this->_retorno?>/<?=$this->tipo?>";

      $.ajax({
          type: "POST",
          url: url,
          data: $("#formulario").serialize(),
          success: function(data)
          {
            //$("#_data_recorte").html('').append(data);
            $("#_load_xx").hide();
            $(".img_ajustes").slideUp("slow");
            $(".img_recortar").slideUp("slow");
            setTimeout(function() {img_final("<?=$this->_retorno?>");}, 500);  
          }
      });
      return false;
  });
});
</script>
<script>
  $(function() {
    $( "#preview-pane" ).draggable();
  });
</script>

<div class="jc-demo-box" id="img_1">

    <img src='<?=$this->_conf['base_url']?>public/img/subidas/originales/<?=$this->_sess->get('img_path')?>' id="target" alt="[Jcrop Example]">

    <div id="preview-pane">
        <div class="preview-container">
            <img src="<?=$this->_conf['base_url']?>public/img/subidas/originales/<?=$this->_sess->get('img_path')?>" class="jcrop-preview" alt="Preview">
        </div>
    </div>

    <div class="description">
        <p>
          <form id="formulario" action="" method="post" onSubmit="return checkCoords();">
              <input type="hidden" name="envio02" value="1">
              <input type="hidden" id="x" name="x">
              <input type="hidden" id="y" name="y">
              <input type="hidden" id="w" name="w">
              <input type="hidden" id="h" name="h">
              <input type="submit" value="Recortar Imagen" class="btn btn-large btn-inverse" id="btn_enviar">
              <span id="_load_xx" style="display:none">
                  <img src="<?=$this->_conf['base_url'] . 'public/img/ajax-loader.gif'?>">
              </span>
          </form>
        </p>
    </div>

    <div class="clearfix"></div>
    <div id="_data_recorte"></div>
</div>