<section id="hero" class="interna">
    <div class="flexslider">
        <ul class="slides">
            <li>
                <div class="wrapper">
                    <div class="mid">
                        <h2 class="anima hideme delay d02">Aprendé a manejar de verdad.</h2>
                    </div>
                </div>
                <div class="circleSm anima hideme delay d06"></div>
                <div class="circleMid anima hideme delay d04"></div>
            </li>
        </ul>   
    </div>
</section>

<i class="divisor"></i>

<section id="pedido" class="centerSection">
    <h3>
        <!-- <a href="commerce.html" class="inner-link">
            <img src="<?php echo $_params['ruta_img']?>arrow-back.svg" alt="Driver's School">
        </a>  -->
        Su Pedido ha sido rechazado.
    </h3>
    <!-- <div class="wrapperSmall">
        <h4>¡Gracias! <br> Tu pedido ha sido recibido.</h4>
    </div> -->
</section>




<script type="text/javascript">
$(document).ready(function() {
    
    $('#social a.cart').hide(); 
    
});
</script>