<main>
    <div class="how-works__header"><h3>SUCCESSFUL PURCHASE</h3></div>
    <section class="how-works">           

        <div class="container">

            <h3 class="text-big" style="text-align:center;margin: 0;padding-top:10px">THANK YOU!</h3>
            <p class="text-small" style="text-align:center;">Click the button below to begin filling out your form.</p>          
            

            <a href="<?=$this->_conf['base_url']?>user/myorders" class="button"><p><strong>GET STARTED</strong></p></a>
        </div>
    </section>
</main>


