<script src="http://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js"></script>
<script>
$(document).ready(function() {

 
  
    
  $('#cargar_trabajo').submit(function(){
    
    
      

     /* $('input[type=checkbox]:checked').each(function() {
          console.log("Checkbox " + $(this).prop("id") +  " (" + $(this).val() + ") Seleccionado");
      });*/

      /*var $fields = $(this).find('input[type=checkbox]:checked');
      if (!$fields.length) {
            alert('Debe seleccionar al menos una categoria');
            return false; 
        }*/

            
     /* if ($("#titulo").val() == "") {
        alert("Debe completar el campo titulo");
        $("#titulo").val('');
        $('#titulo').focus();     
        //$("#titulo").attr('placeholder', 'Titulo');
        return false;        
      }*/

     /* if ($("#video").val() == "") {
        alert("Debe completar el campo video");
        $('#video').focus();     
        //$("#titulo").attr('placeholder', 'Titulo');
        return false;        
      }*/

     

      /*if($('._load_img_final_medidas').children().length == 0){
        alert("Debe seleccionar una imagen");
        return false; 
      }*/
      
      
      
      return true;
    
  
  });
  
  
  
});

</script>



<div class="row wrapper">
    <div class="col-lg-10">
        <h2>FAQs</h2>        
    </div>
    <div class="col-lg-2"></div>
</div>


 <div class="row wrapper wrapper-content">  
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="row">
                
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Cargar</h5>
                        </div>



                        <form class="form-horizontal" id="cargar_trabajo" action="" method="POST" role="form" enctype="multipart/form-data">
                        <input type="hidden" name="envio01" value="1" />        
                        <input type="hidden" name="_csrf" value="<?=$this->_sess->get('_csrf')?>">                          
                       
                        
                        <div class="ibox-content"> 
                          <div class="form-group">
                              <label class="col-lg-2 control-label">Pregunta</label>
                              <div class="col-lg-9">
                                <textarea class="form-control" id="pregunta" name="pregunta"><?php if(isset($this->data['pregunta'])) echo $this->data['pregunta']?></textarea>
                                  <script>
                                      CKEDITOR.replace('pregunta', {
                                          extraPlugins: 'colorbutton'
                                      });
                                  </script>                               
                                 
                              </div>
                          </div>
                        </div>


                        <div class="ibox-content"> 
                          <div class="form-group">
                              <label class="col-lg-2 control-label">Respueta</label>
                              <div class="col-lg-9">
                                <textarea class="form-control" id="respuesta" name="respuesta"><?php if(isset($this->data['respuesta'])) echo $this->data['respuesta']?></textarea>
                                  <script>
                                      CKEDITOR.replace('respuesta', {
                                          extraPlugins: 'colorbutton'
                                      });
                                  </script>                               
                                 
                              </div>
                          </div>
                        </div>



                      
                      

                        <div class="ibox-content">
                          <div class="row">
                                <div class="form-group">
                                    <div class="col-lg-offset-2 col-lg-2">
                                      <input type="submit" class="btn btn-success" id="validatex" nname="cargar" value="Guardar" />                                      
                                    </div>                                                                       
                                </div>
                                
                              
                            </div>                            
                        </div>
                       </form> 
                    </div>
                </div>
          </div>
      </div>
  </div>
</div> 


<!-- <form class="form-horizontal" id="cargar_trabajo" action="" method="POST" role="form" autocomplete="off">
  <input type="hidden" name="envio01" value="1" />    
  <input type="hidden" name="_csrf" value="<?=$this->_sess->get('_csrf')?>">

    <div class="wrapper wrapper-content ecommerce ">
        <div class="row">
            <div class="col-lg-12">
                <div class="tabs-container">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#tab-1">Ingles</a></li>
                        <li class=""><a data-toggle="tab" href="#tab-2">Español</a></li>
                        <li class=""><a data-toggle="tab" href="#tab-3">Italiano</a></li>
                        <li class=""><a data-toggle="tab" href="#tab-4">Guardar</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane active">
                            <div class="panel-body">
                                <fieldset class="form-horizontal">


                                  <div class="form-group">
                                      <label class="col-lg-2 control-label">Pregunta</label>
                                      <div class="col-lg-9">
                                        <textarea class="form-control" id="pregunta_eng" name="pregunta[1]"><?php if(isset($this->data['pregunta'])) echo $this->data['pregunta']?></textarea>
                                          <script>
                                              CKEDITOR.replace('pregunta_eng', {
                                                  extraPlugins: 'colorbutton'
                                              });
                                          </script>                               
                                         
                                      </div>
                                  </div>
                                  <div class="form-group">
                                      <label class="col-lg-2 control-label">Respueta</label>
                                      <div class="col-lg-9">
                                        <textarea class="form-control" id="respuesta_eng" name="respuesta[1]"><?php if(isset($this->data['respuesta'])) echo $this->data['respuesta']?></textarea>
                                          <script>
                                              CKEDITOR.replace('respuesta_eng', {
                                                  extraPlugins: 'colorbutton'
                                              });
                                          </script>                               
                                         
                                      </div>
                                  </div>


                                </fieldset>
                            </div>
                        </div>

                        <div id="tab-2" class="tab-pane">
                            <div class="panel-body">
                                <fieldset class="form-horizontal">
                                   
                                  <div class="form-group">
                                      <label class="col-lg-2 control-label">Pregunta</label>
                                      <div class="col-lg-9">
                                        <textarea class="form-control" id="pregunta_esp" name="pregunta[2]"><?php if(isset($this->data['pregunta'])) echo $this->data['pregunta']?></textarea>
                                          <script>
                                              CKEDITOR.replace('pregunta_esp', {
                                                  extraPlugins: 'colorbutton'
                                              });
                                          </script>                               
                                         
                                      </div>
                                  </div>
                                  <div class="form-group">
                                      <label class="col-lg-2 control-label">Respueta</label>
                                      <div class="col-lg-9">
                                        <textarea class="form-control" id="respuesta_esp" name="respuesta[2]"><?php if(isset($this->data['respuesta'])) echo $this->data['respuesta']?></textarea>
                                          <script>
                                              CKEDITOR.replace('respuesta_esp', {
                                                  extraPlugins: 'colorbutton'
                                              });
                                          </script>                               
                                         
                                      </div>
                                  </div>
                                   

                                </fieldset>
                            </div>
                        </div>

                        <div id="tab-3" class="tab-pane">
                            <div class="panel-body">
                                <fieldset class="form-horizontal">
                                   

                                   <div class="form-group">
                                      <label class="col-lg-2 control-label">Pregunta</label>
                                      <div class="col-lg-9">
                                        <textarea class="form-control" id="pregunta_ita" name="pregunta[3]"><?php if(isset($this->data['pregunta'])) echo $this->data['pregunta']?></textarea>
                                          <script>
                                              CKEDITOR.replace('pregunta_ita', {
                                                  extraPlugins: 'colorbutton'
                                              });
                                          </script>                               
                                         
                                      </div>
                                  </div>
                                  <div class="form-group">
                                      <label class="col-lg-2 control-label">Respueta</label>
                                      <div class="col-lg-9">
                                        <textarea class="form-control" id="respuesta_ita" name="respuesta[3]"><?php if(isset($this->data['respuesta'])) echo $this->data['respuesta']?></textarea>
                                          <script>
                                              CKEDITOR.replace('respuesta_ita', {
                                                  extraPlugins: 'colorbutton'
                                              });
                                          </script>                               
                                         
                                      </div>
                                  </div>
                                  
                                </fieldset>
                            </div>
                        </div>

                        <div id="tab-4" class="tab-pane">
                            <div class="panel-body">
                                <fieldset class="form-horizontal">


                                  <div class="form-group">
                                      <div class="col-lg-2">
                                        <input type="submit" class="btn btn btn-success" id="validatex" name="cargar" value="Guardar" />                                      
                                      </div>                                                                       
                                  </div>                                   


                                </fieldset>
                            </div>
                        </div>

                       
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

 -->

