<main>
    <nav class="nav-breadcrumb" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item" ><a href="<?=$this->_conf['base_url']?>user/myaccount">My account</a></li>
            <?php if($this->user['estado'] == 'customer'):?>
            <li class="breadcrumb-item"><a href="<?=$this->_conf['base_url']?>user/myorders">My orders</a></li>
            <?php endif?>
            <li class="breadcrumb-item" ><a href="<?=$this->_conf['base_url']?>user/signout">Sign Out</a></li>
        </ol>
    </nav>

    <section class="cart whity">
        <h1>The Quick Divorce - MSA + PPA</h1>
   <div class="containerForm">
       <aside>             
            <h2>MENU</h2>    
            
            <ul id="navform">
                <li data-section="Divorce" class="active">Divorce</li>
                <li data-section="Wife">Wife </li>
                <li data-section="Wife-Financial">Wife Financial</li>
                <li data-section="Husband">Husband</li>
                <li data-section="Husband-Financial">Husband Financial</li>
                <li data-section="Children">Children</li>
                <li data-section="Parenting-Plan">Parenting Plan</li>
                <li data-section="Property">Property</li>
                <li data-section="Child-Support">Child Support</li>
                <li data-section="Name-Change">Name Change</li>
            </ul>

       </aside>
       <main>
           <section id="Divorce" style="display: block;">
               <div class="information contForm">
                    <h2>Information</h2>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td width="50%">Is this a Same-Sex Relationship?</td>
                            <td width="10%"></td>
                            <td width="20%"><input type="radio" name="SameSex" value="No"> <label>No</label></td>
                            <td width="20%"><input type="radio" name="SameSex" value="Yes"> <label>Yes</label></td>
                        </tr>
                        <tr id="sexo">                            
                            <td width="50%"></td>
                            <td width="10%"></td>
                            <td width="20%"><input type="radio" name="SameSexS" value="MM"> <label>M/M</label></td>
                            <td width="20%"><input type="radio" name="SameSexS" value="FF"> <label>F/F</label></td>
                        </tr>
                        <tr>
                            <td width="50%">Person Filing the Seperation</td>
                            <td width="10%"></td>
                            <td width="20%"><input type="radio" name="FilingSeparation" value="Husband"> <label>Husband</label></td>
                            <td width="20%"><input type="radio" name="FilingSeparation" value="Wife"> <label>Wife</label></td>
                        </tr>
                        <tr>
                            <td width="50%">Were you married in the United States?</td>
                            <td width="10%"></td>
                            <td width="20%"><input type="radio" name="MarriageUS" value="Yes"> <label>Yes</label></td>
                            <td width="20%"><input type="radio" name="MarriageUS" value="No"> <label>No</label></td>
                        </tr>
                        <tr>
                            <td width="50%">Marriage City</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="MarriageCity" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Marriage State</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2">
                                <select size="1" name="MarriageState" class="formfont">
                                    <option>State</option>
                                    <option>AK</option>
                                    <option>AL</option>
                                    <option>AR</option>
                                    <option>AZ</option>
                                    <option>CA</option>
                                    <option>CO</option>
                                    <option>CT</option>
                                    <option>DC</option>
                                    <option>DE</option>
                                    <option>FL</option>
                                    <option>GA</option>
                                    <option>HI</option>
                                    <option>IA</option>
                                    <option>ID</option>
                                    <option>IL</option>
                                    <option>IN</option>
                                    <option>KS</option>
                                    <option>KY</option>
                                    <option>LA</option>
                                    <option>MA</option>
                                    <option>MD</option>
                                    <option>ME</option>
                                    <option>MI</option>
                                    <option>MN</option>
                                    <option>MO</option>
                                    <option>MS</option>
                                    <option>MT</option>
                                    <option>NC</option>
                                    <option>ND</option>
                                    <option>NE</option>
                                    <option>NH</option>
                                    <option>NJ</option>
                                    <option>NM</option>
                                    <option>NV</option>
                                    <option>NY</option>
                                    <option>OH</option>
                                    <option>OK</option>
                                    <option>OR</option>
                                    <option>PA</option>
                                    <option>RI</option>
                                    <option>SC</option>
                                    <option>SD</option>
                                    <option>TN</option>
                                    <option>TX</option>
                                    <option>UT</option>
                                    <option>VT</option>
                                    <option>VA</option>
                                    <option>WA</option>
                                    <option>WI</option>
                                    <option>WV</option>
                                    <option>WY</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td width="50%">Date of Marriage (MM/DD/YYYY)</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2">
                                <input type="date" name="dateMarriage">
                            </td>
                        </tr>
                        <tr>
                            <td width="50%">Date of Separation (MM/DD/YYYY)</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2">
                                <input type="date" name="dateSeparation">
                            </td>
                        </tr>
                        <tr>
                            <td width="50%">Do you have any minor children from this marriage?</td>
                            <td width="10%"></td>
                            <td width="20%"><input type="radio" name="children" value="No"> <label>No</label></td>
                            <td width="20%"><input type="radio" name="children" value="Yes"> <label>Yes</label></td>
                        </tr>
                    </table>
                   
               </div>
               <div class="residency contForm">
                   <h2>Residency</h2>
                    <table cellpadding="0" cellspacing="0" width="100%">
                       <tr>
                           <td colspan="3"><strong>Domicile:</strong><br> At least one of you must have lived in Florida for the past six months, and lived in the county where the divorce will be filed for the past 90 days.</td>
                       </tr>
                       <tr>
                           <td><input type="radio" name="domicile" value="Wife"></td>
                           <td width="5%"></td>
                           <td><strong>Wife</strong> has lived in Florida for the past six months and in the filing county for the past 90 days.</td>
                       </tr>
                       <tr>
                           <td><input type="radio" name="domicile" value="Husband"></td>
                           <td width="5%"></td>
                           <td><strong>Husband</strong> has lived in Florida for the past six months and in the filing county for the past 90 days.</td>
                       </tr>
                       <tr>
                           <td><input type="radio" name="domicile" value="Both Partners"></td>
                           <td width="5%"></td>
                           <td><strong>Both spouses</strong> have lived in Florida for the past six months and in the filing county for the past 90 days.</td>
                       </tr>
                       <tr><td colspan="3"><hr></td></tr>
                       <tr>
                           <td colspan="3"><strong>Military:</strong> <br> Is Wife on active duty in the military?</td>
                       </tr>
                       <tr>
                           <td><input type="radio" name="military-1" value="Yes"></td>
                           <td width="5%"></td>
                           <td><strong>Yes</strong></td>
                       </tr>
                       <tr>
                           <td><input type="radio" name="military-1" value="No"></td>
                           <td width="5%"></td>
                           <td><strong>No</strong></td>
                       </tr>
                       <tr>
                           <td colspan="3">Is the Husband on active duty in the military?</td>
                       </tr>
                       <tr>
                           <td><input type="radio" name="military-2" value="Yes"></td>
                           <td width="5%"></td>
                           <td><strong>Yes</strong></td>
                       </tr>
                       <tr>
                           <td><input type="radio" name="military-2" value="No"></td>
                           <td width="5%"></td>
                           <td><strong>No</strong></td>
                       </tr>
                       <tr><td colspan="3"><hr></td></tr>
                       <tr>
                           <td colspan="3"><strong>Other Court Cases:</strong><br> Are there any other domestic/family law cases pending concerning the parties and/or their children in any court? </td>
                       </tr>
                       <tr>
                           <td><input type="radio" name="other-case" value="Yes"></td>
                           <td width="5%"></td>
                           <td><strong>Yes</strong></td>
                       </tr>
                       <tr>
                           <td><input type="radio" name="other-case" value="No"></td>
                           <td width="5%"></td>
                           <td><strong>No</strong></td>
                       </tr>
                   </table>
               </div>
           </section>

           <section id="Wife" style="display: none;">
               <div class="information contForm">
                    <h2>Information</h2>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td width="50%">First Name</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="Wife-firstname" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Middle Name</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="Wife-middlename" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Last Name</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="Wife-lastname" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Birth Date (MM/DD/YYYY)</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2">
                                <input type="date" name="Wife-birth">
                            </td>
                        </tr>
                        <tr>
                            <td width="50%">Maiden Name</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="Wife-maidenname" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Is the Wife currently pregnant?</td>
                            <td width="10%"></td>
                            <td width="20%"><input type="radio" name="Wife-pregnant" value="No"> <label>No</label></td>
                            <td width="20%"><input type="radio" name="Wife-pregnant" value="Yes"> <label>Yes</label></td>
                        </tr>
                        <tr>
                            <td width="50%">Street Address</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="Wife-address" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">City and State</td>
                            <td width="10%"></td>
                            <td width="20%"><input type="text" name="Wife-city" value="" placeholder="City"></td>
                            <td width="20%" align="center">
                                <select size="1" name="WifeState" class="formfont">
                                  <option>State</option>
                                  <option>FL</option>
                                  <option>AK</option>
                                  <option>AL</option>
                                  <option>AR</option>
                                  <option>AZ</option>
                                  <option>CA</option>
                                  <option>CO</option>
                                  <option>CT</option>
                                  <option>DC</option>
                                  <option>DE</option>
                                  <option>FL</option>
                                  <option>GA</option>
                                  <option>HI</option>
                                  <option>IA</option>
                                  <option>ID</option>
                                  <option>IL</option>
                                  <option>IN</option>
                                  <option>KS</option>
                                  <option>KY</option>
                                  <option>LA</option>
                                  <option>MA</option>
                                  <option>MD</option>
                                  <option>ME</option>
                                  <option>MI</option>
                                  <option>MN</option>
                                  <option>MO</option>
                                  <option>MS</option>
                                  <option>MT</option>
                                  <option>NC</option>
                                  <option>ND</option>
                                  <option>NE</option>
                                  <option>NH</option>
                                  <option>NJ</option>
                                  <option>NM</option>
                                  <option>NV</option>
                                  <option>NY</option>
                                  <option>OH</option>
                                  <option>OK</option>
                                  <option>OR</option>
                                  <option>PA</option>
                                  <option>RI</option>
                                  <option>SC</option>
                                  <option>SD</option>
                                  <option>TN</option>
                                  <option>TX</option>
                                  <option>UT</option>
                                  <option>VT</option>
                                  <option>VA</option>
                                  <option>WA</option>
                                  <option>WI</option>
                                  <option>WV</option>
                                  <option>WY</option>
                              </select>
                            </td>
                        </tr>
                        <tr>
                            <td width="50%">Zip Code</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="number" name="Wife-zipcode" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Phone</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="number" name="Wife-phone" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Fax Number (optional)</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="number" name="Wife-fax" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">E-Mail Address</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="email" name="Wife-email" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">County</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="Wife-County" value=""></td>
                        </tr>
                    </table>                   
               </div>
               <div class="identification contForm">
                   <h2>Identification</h2>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td width="50%">Birth State (or country if not USA)</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="wife-BirthState" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Driver's License Number</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="wife-DriverLicenceNumber" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Driver's License State of Issuance</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2">
                                <select size="1" name="wifeDriverLicenceState" class="formfont">
                                  <option>State</option>
                                  <option>FL</option>
                                  <option>AK</option>
                                  <option>AL</option>
                                  <option>AR</option>
                                  <option>AZ</option>
                                  <option>CA</option>
                                  <option>CO</option>
                                  <option>CT</option>
                                  <option>DC</option>
                                  <option>DE</option>
                                  <option>FL</option>
                                  <option>GA</option>
                                  <option>HI</option>
                                  <option>IA</option>
                                  <option>ID</option>
                                  <option>IL</option>
                                  <option>IN</option>
                                  <option>KS</option>
                                  <option>KY</option>
                                  <option>LA</option>
                                  <option>MA</option>
                                  <option>MD</option>
                                  <option>ME</option>
                                  <option>MI</option>
                                  <option>MN</option>
                                  <option>MO</option>
                                  <option>MS</option>
                                  <option>MT</option>
                                  <option>NC</option>
                                  <option>ND</option>
                                  <option>NE</option>
                                  <option>NH</option>
                                  <option>NJ</option>
                                  <option>NM</option>
                                  <option>NV</option>
                                  <option>NY</option>
                                  <option>OH</option>
                                  <option>OK</option>
                                  <option>OR</option>
                                  <option>PA</option>
                                  <option>RI</option>
                                  <option>SC</option>
                                  <option>SD</option>
                                  <option>TN</option>
                                  <option>TX</option>
                                  <option>UT</option>
                                  <option>VT</option>
                                  <option>VA</option>
                                  <option>WA</option>
                                  <option>WI</option>
                                  <option>WV</option>
                                  <option>WY</option>
                              </select>
                            </td>
                        </tr>
                    </table>
               </div>
               <div class="employer contForm">
                   <h2>Employer</h2>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td width="50%">Is the Partner currently employed?</td>
                            <td width="10%"></td>
                            <td width="20%"><input type="radio" name="wife-employed" value="No"> <label>No</label></td>
                            <td width="20%"><input type="radio" name="wife-employed" value="Yes"> <label>Yes</label></td>
                        </tr>
                        <tr>
                            <td width="50%">Occupation</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="wife-OccupationEmployed" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Employer</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="wife-EmployerEmployed" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Employment Address</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="wife-EmployedAddress" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Employment Address Line 2</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="wife-EmployedAddress2" value=""></td>
                        </tr><tr>
                            <td width="50%">City and State</td>
                            <td width="10%"></td>
                            <td width="20%"><input type="text" name="wife-cityEmployed" value="" placeholder="City"></td>
                            <td width="20%" align="center">
                                <select size="1" name="wifeStateEmployed" class="formfont">
                                  <option>State</option>
                                  <option>FL</option>
                                  <option>AK</option>
                                  <option>AL</option>
                                  <option>AR</option>
                                  <option>AZ</option>
                                  <option>CA</option>
                                  <option>CO</option>
                                  <option>CT</option>
                                  <option>DC</option>
                                  <option>DE</option>
                                  <option>FL</option>
                                  <option>GA</option>
                                  <option>HI</option>
                                  <option>IA</option>
                                  <option>ID</option>
                                  <option>IL</option>
                                  <option>IN</option>
                                  <option>KS</option>
                                  <option>KY</option>
                                  <option>LA</option>
                                  <option>MA</option>
                                  <option>MD</option>
                                  <option>ME</option>
                                  <option>MI</option>
                                  <option>MN</option>
                                  <option>MO</option>
                                  <option>MS</option>
                                  <option>MT</option>
                                  <option>NC</option>
                                  <option>ND</option>
                                  <option>NE</option>
                                  <option>NH</option>
                                  <option>NJ</option>
                                  <option>NM</option>
                                  <option>NV</option>
                                  <option>NY</option>
                                  <option>OH</option>
                                  <option>OK</option>
                                  <option>OR</option>
                                  <option>PA</option>
                                  <option>RI</option>
                                  <option>SC</option>
                                  <option>SD</option>
                                  <option>TN</option>
                                  <option>TX</option>
                                  <option>UT</option>
                                  <option>VT</option>
                                  <option>VA</option>
                                  <option>WA</option>
                                  <option>WI</option>
                                  <option>WV</option>
                                  <option>WY</option>
                              </select>
                            </td>
                        </tr>
                        <tr>
                            <td width="50%">Zip Code</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="number" name="wife-zipcodeEmployed" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Phone</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="number" name="wife-phoneEmployed" value=""></td>
                        </tr>
                    </table>
               </div>
           </section>

           <section id="Wife-Financial" style="display: none;">
               <div class="income contForm">
                   <h2>Wife Income</h2>
                   <table cellpadding="0" cellspacing="0" width="100%">
                       <tr>
                           <td colspan="3"><strong>Monthly Income</strong></td>
                       </tr>
                       <tr>
                           <td width="60%">Wages and Salaries</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-wageSalaries" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Interest and Dividend Income</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-InterestDividend" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Business Income (Self-Employment)</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-BusinessIncome" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Alimony from Prior Marriage</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-AlmonyMarriage" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Disability Benefits/SSI</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-DisabilityBenefits" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Workers' Compensation</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-WorkersCompensation" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Unemployment Benefits</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-UnemployedBenefits" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Pension, Retirement, or Annuity payments</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-PensionRetirement" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Social Security Benefits</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-socialSecurityBenefits" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Other Income</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-Other" value=""></td>
                       </tr>
                       <tr>
                           <td colspan="3"><strong>Monthly Deductions from Gross Income</strong></td>
                       </tr>
                       <tr>
                           <td width="60%">Income Taxes (Federal and State)</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-IncomeTaxes" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">FICA (Soc.Sec.)/Self-Employment Taxes</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-FICA" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Medicare</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-Medicare" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Health Insurance (not including portion paid for children)</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-HealthInsurance" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">State Industrial Insurance Deductions</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-StateIndustrialInsurance" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Mandatory Union Dues</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-MandatoryUnionDues" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Mandatory Pension Plan Payments</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-MandatoryPensionPlan" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Alimony Paid for Prior Marriage</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-AlimonyPaidPrior" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Normal Business Expenses</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="WifeFinancial-NormalBusinessExpenses" value=""></td>
                       </tr>
                   </table>
               </div>
               <div class="childcare contForm">
                   <h2>Wife Child Care Expenses</h2>
                   <table cellpadding="0" cellspacing="0" width="100%">
                       <tr>
                           <td colspan="3"><strong>Monthly Child Care Expenses</strong></td>
                       </tr>
                       <tr>
                           <td width="60%">Child Health Insurance Premiums</td>
                           <td width="10%"></td>
                           <td width="30%" colspan="2">$<input type="number" name="WifeFinancial-ChildHealthInsurance" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Extraordinary Child Health Care Costs</td>
                           <td width="10%"></td>
                           <td width="30%" colspan="2">$<input type="number" name="WifeFinancial-InterestDividend" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Daycare Expenses</td>
                           <td width="10%"></td>
                           <td width="30%" colspan="2">$<input type="number" name="WifeFinancial-Daycare" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Education Expenses</td>
                           <td width="10%"></td>
                           <td width="30%" colspan="2">$<input type="number" name="WifeFinancial-Education" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Long Distance Transportation Expenses</td>
                           <td width="10%"></td>
                           <td width="30%" colspan="2">$<input type="number" name="WifeFinancial-Transportation" value=""></td>
                       </tr>
                        <tr>
                            <td width="60%">Does the Wife have any other special child care expenses?</td>
                            <td width="10%"></td>
                            <td width="15%"><input type="radio" name="Wife-specialchildcare" value="No"> <label>No</label></td>
                            <td width="15%"><input type="radio" name="Wife-specialchildcare" value="Yes"> <label>Yes</label></td>
                        </tr>
                   </table>
               </div>
               <div class="otherchild contForm">
                   <h2>Wife Other Child Support</h2>
                   <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td width="60%">Does the Partner 1 currently pay child support for other children not from this marriage?</td>
                            <td width="10%"></td>
                            <td width="15%"><input type="radio" name="Wife-otherchildsupport" value="No"> <label>No</label></td>
                            <td width="15%"><input type="radio" name="Wife-otherchildsupport" value="Yes"> <label>Yes</label></td>
                        </tr>
                   </table>
               </div>
           </section>

           <section id="Husband" style="display: none;">
               <div class="information contForm">
                    <h2>Information</h2>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td width="50%">First Name</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="husband-firstname" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Middle Name</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="husband-middlename" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Last Name</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="husband-lastname" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Birth Date (MM/DD/YYYY)</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2">
                                <input type="date" name="husband-birth">
                            </td>
                        </tr>
                        <tr>
                            <td width="50%">Street Address</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="husband-address" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">City and State</td>
                            <td width="10%"></td>
                            <td width="20%"><input type="text" name="husband-city" value="" placeholder="City"></td>
                            <td width="20%" align="center">
                                <select size="1" name="husbandState" class="formfont">
                                  <option>State</option>
                                  <option>FL</option>
                                  <option>AK</option>
                                  <option>AL</option>
                                  <option>AR</option>
                                  <option>AZ</option>
                                  <option>CA</option>
                                  <option>CO</option>
                                  <option>CT</option>
                                  <option>DC</option>
                                  <option>DE</option>
                                  <option>FL</option>
                                  <option>GA</option>
                                  <option>HI</option>
                                  <option>IA</option>
                                  <option>ID</option>
                                  <option>IL</option>
                                  <option>IN</option>
                                  <option>KS</option>
                                  <option>KY</option>
                                  <option>LA</option>
                                  <option>MA</option>
                                  <option>MD</option>
                                  <option>ME</option>
                                  <option>MI</option>
                                  <option>MN</option>
                                  <option>MO</option>
                                  <option>MS</option>
                                  <option>MT</option>
                                  <option>NC</option>
                                  <option>ND</option>
                                  <option>NE</option>
                                  <option>NH</option>
                                  <option>NJ</option>
                                  <option>NM</option>
                                  <option>NV</option>
                                  <option>NY</option>
                                  <option>OH</option>
                                  <option>OK</option>
                                  <option>OR</option>
                                  <option>PA</option>
                                  <option>RI</option>
                                  <option>SC</option>
                                  <option>SD</option>
                                  <option>TN</option>
                                  <option>TX</option>
                                  <option>UT</option>
                                  <option>VT</option>
                                  <option>VA</option>
                                  <option>WA</option>
                                  <option>WI</option>
                                  <option>WV</option>
                                  <option>WY</option>
                              </select>
                            </td>
                        </tr>
                        <tr>
                            <td width="50%">Zip Code</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="number" name="husband-zipcode" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Phone</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="number" name="husband-phone" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Fax Number (optional)</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="number" name="husband-fax" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">E-Mail Address</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="email" name="husband-email" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">County</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="husband-County" value=""></td>
                        </tr>
                    </table>                   
               </div>
               <div class="identification contForm">
                   <h2>Identification</h2>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td width="50%">Birth State (or country if not USA)</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="husband-BirthState" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Driver's License Number</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="husband-DriverLicenceNumber" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Driver's License State of Issuance</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2">
                                <select size="1" name="husbandDriverLicenceState" class="formfont">
                                  <option>State</option>
                                  <option>FL</option>
                                  <option>AK</option>
                                  <option>AL</option>
                                  <option>AR</option>
                                  <option>AZ</option>
                                  <option>CA</option>
                                  <option>CO</option>
                                  <option>CT</option>
                                  <option>DC</option>
                                  <option>DE</option>
                                  <option>FL</option>
                                  <option>GA</option>
                                  <option>HI</option>
                                  <option>IA</option>
                                  <option>ID</option>
                                  <option>IL</option>
                                  <option>IN</option>
                                  <option>KS</option>
                                  <option>KY</option>
                                  <option>LA</option>
                                  <option>MA</option>
                                  <option>MD</option>
                                  <option>ME</option>
                                  <option>MI</option>
                                  <option>MN</option>
                                  <option>MO</option>
                                  <option>MS</option>
                                  <option>MT</option>
                                  <option>NC</option>
                                  <option>ND</option>
                                  <option>NE</option>
                                  <option>NH</option>
                                  <option>NJ</option>
                                  <option>NM</option>
                                  <option>NV</option>
                                  <option>NY</option>
                                  <option>OH</option>
                                  <option>OK</option>
                                  <option>OR</option>
                                  <option>PA</option>
                                  <option>RI</option>
                                  <option>SC</option>
                                  <option>SD</option>
                                  <option>TN</option>
                                  <option>TX</option>
                                  <option>UT</option>
                                  <option>VT</option>
                                  <option>VA</option>
                                  <option>WA</option>
                                  <option>WI</option>
                                  <option>WV</option>
                                  <option>WY</option>
                              </select>
                            </td>
                        </tr>
                    </table>
               </div>
               <div class="employer contForm">
                   <h2>Employer</h2>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td width="50%">Is the Partner currently employed?</td>
                            <td width="10%"></td>
                            <td width="20%"><input type="radio" name="husband-employed" value="No"> <label>No</label></td>
                            <td width="20%"><input type="radio" name="husband-employed" value="Yes"> <label>Yes</label></td>
                        </tr>
                        <tr>
                            <td width="50%">Occupation</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="husband-OccupationEmployed" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Employer</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="husband-EmployerEmployed" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Employment Address</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="husband-EmployedAddress" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Employment Address Line 2</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="text" name="husband-EmployedAddress2" value=""></td>
                        </tr><tr>
                            <td width="50%">City and State</td>
                            <td width="10%"></td>
                            <td width="20%"><input type="text" name="husband-cityEmployed" value="" placeholder="City"></td>
                            <td width="20%" align="center">
                                <select size="1" name="husbandStateEmployed" class="formfont">
                                  <option>State</option>
                                  <option>FL</option>
                                  <option>AK</option>
                                  <option>AL</option>
                                  <option>AR</option>
                                  <option>AZ</option>
                                  <option>CA</option>
                                  <option>CO</option>
                                  <option>CT</option>
                                  <option>DC</option>
                                  <option>DE</option>
                                  <option>FL</option>
                                  <option>GA</option>
                                  <option>HI</option>
                                  <option>IA</option>
                                  <option>ID</option>
                                  <option>IL</option>
                                  <option>IN</option>
                                  <option>KS</option>
                                  <option>KY</option>
                                  <option>LA</option>
                                  <option>MA</option>
                                  <option>MD</option>
                                  <option>ME</option>
                                  <option>MI</option>
                                  <option>MN</option>
                                  <option>MO</option>
                                  <option>MS</option>
                                  <option>MT</option>
                                  <option>NC</option>
                                  <option>ND</option>
                                  <option>NE</option>
                                  <option>NH</option>
                                  <option>NJ</option>
                                  <option>NM</option>
                                  <option>NV</option>
                                  <option>NY</option>
                                  <option>OH</option>
                                  <option>OK</option>
                                  <option>OR</option>
                                  <option>PA</option>
                                  <option>RI</option>
                                  <option>SC</option>
                                  <option>SD</option>
                                  <option>TN</option>
                                  <option>TX</option>
                                  <option>UT</option>
                                  <option>VT</option>
                                  <option>VA</option>
                                  <option>WA</option>
                                  <option>WI</option>
                                  <option>WV</option>
                                  <option>WY</option>
                              </select>
                            </td>
                        </tr>
                        <tr>
                            <td width="50%">Zip Code</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="number" name="husband-zipcodeEmployed" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Phone</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="2"><input type="number" name="husband-phoneEmployed" value=""></td>
                        </tr>
                    </table>
               </div>
           </section>

           <section id="Husband-Financial" style="display: none;">
               <div class="income contForm">
                   <h2>Husband Income</h2>
                   <table cellpadding="0" cellspacing="0" width="100%">
                       <tr>
                           <td colspan="3"><strong>Monthly Income</strong></td>
                       </tr>
                       <tr>
                           <td width="60%">Wages and Salaries</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-wageSalaries" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Interest and Dividend Income</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-InterestDividend" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Business Income (Self-Employment)</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-BusinessIncome" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Alimony from Prior Marriage</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-AlmonyMarriage" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Disability Benefits/SSI</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-DisabilityBenefits" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Workers' Compensation</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-WorkersCompensation" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Unemployment Benefits</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-UnemployedBenefits" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Pension, Retirement, or Annuity payments</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-PensionRetirement" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Social Security Benefits</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-socialSecurityBenefits" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Other Income</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-Other" value=""></td>
                       </tr>
                       <tr>
                           <td colspan="3"><strong>Monthly Deductions from Gross Income</strong></td>
                       </tr>
                       <tr>
                           <td width="60%">Income Taxes (Federal and State)</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-IncomeTaxes" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">FICA (Soc.Sec.)/Self-Employment Taxes</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-FICA" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Medicare</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-Medicare" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Health Insurance (not including portion paid for children)</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-HealthInsurance" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">State Industrial Insurance Deductions</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-StateIndustrialInsurance" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Mandatory Union Dues</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-MandatoryUnionDues" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Mandatory Pension Plan Payments</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-MandatoryPensionPlan" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Alimony Paid for Prior Marriage</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-AlimonyPaidPrior" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Normal Business Expenses</td>
                           <td width="10%"></td>
                           <td width="30%">$<input type="number" name="HusbandFinancial-NormalBusinessExpenses" value=""></td>
                       </tr>
                   </table>
               </div>
               <div class="childcare contForm">
                   <h2>Husband Child Care Expenses</h2>
                   <table cellpadding="0" cellspacing="0" width="100%">
                       <tr>
                           <td colspan="3"><strong>Monthly Child Care Expenses</strong></td>
                       </tr>
                       <tr>
                           <td width="60%">Child Health Insurance Premiums</td>
                           <td width="10%"></td>
                           <td width="30%" colspan="2">$<input type="number" name="HusbandFinancial-ChildHealthInsurance" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Extraordinary Child Health Care Costs</td>
                           <td width="10%"></td>
                           <td width="30%" colspan="2">$<input type="number" name="HusbandFinancial-InterestDividend" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Daycare Expenses</td>
                           <td width="10%"></td>
                           <td width="30%" colspan="2">$<input type="number" name="HusbandFinancial-Daycare" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Education Expenses</td>
                           <td width="10%"></td>
                           <td width="30%" colspan="2">$<input type="number" name="HusbandFinancial-Education" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%">Long Distance Transportation Expenses</td>
                           <td width="10%"></td>
                           <td width="30%" colspan="2">$<input type="number" name="HusbandFinancial-Transportation" value=""></td>
                       </tr>
                        <tr>
                            <td width="60%">Does the Husband have any other special child care expenses?</td>
                            <td width="10%"></td>
                            <td width="15%"><input type="radio" name="Husband-specialchildcare" value="No"> <label>No</label></td>
                            <td width="15%"><input type="radio" name="Husband-specialchildcare" value="Yes"> <label>Yes</label></td>
                        </tr>
                   </table>
               </div>
               <div class="otherchild contForm">
                   <h2>Husband Other Child Support</h2>
                   <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td width="60%">Does the Husband currently pay child support for other children not from this marriage?</td>
                            <td width="10%"></td>
                            <td width="15%"><input type="radio" name="Husband-otherchildsupport" value="No"> <label>No</label></td>
                            <td width="15%"><input type="radio" name="Husband-otherchildsupport" value="Yes"> <label>Yes</label></td>
                        </tr>
                   </table>
               </div>
           </section>

           <section id="Children" style="display: none;">
               <div class="frommarriage contForm">
                   <h2>Children From Partnership</h2>
                   <table cellpadding="0" cellspacing="0" width="100%">
                       <tr>
                           <td colspan="3">List the minor children from this partnership</td>
                       </tr>
                   </table>

                    <table cellpadding="0" cellspacing="0" width="100%" id="child">
                        <tr>
                            <td colspan="5"><strong class="title-child">Child:</strong></td>
                        </tr>
                        <tr>
                            <td width="50%">Child's First Name</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="3"><input type="text" name="child-firstname" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Middle Name</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="3"><input type="text" name="child-middlename" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Last Name</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="3"><input type="text" name="child-lastname" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">Birth Date (MM/DD/YYYY)</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="3">
                                <input type="date" name="child-birth">
                            </td>
                        </tr>
                        <tr>
                            <td width="50%">Gender</td>
                            <td width="10%"></td>
                            <td width="15%"><input type="radio" name="child-gender" value="Male"> <label>Male</label></td>
                            <td width="15%" colspan="2"><input type="radio" name="child-gender" value="Female"> <label>Female</label></td>
                        </tr>
                        <tr>
                            <td width="50%">Birth Place (City and State)</td>
                            <td width="10%"></td>
                            <td width="40%" colspan="3"><input type="text" name="child-birthPlace" value=""></td>
                        </tr>
                        <tr>
                            <td width="50%">With Whom is Child Currently Living?</td>
                            <td width="10%"></td>
                            <td width="13%"><input type="radio" name="child-currentlyLiving" value="Mother"> <label>Mother</label></td>
                            <td width="14%"><input type="radio" name="child-currentlyLiving" value="Father"> <label>Father</label></td>
                            <td width="13%"><input type="radio" name="child-currentlyLiving" value="Other"> <label>Other</label></td>
                        </tr>
                    </table>
                    <div id="duplicate-child"></div>
                    <div class="buttons" style="padding-top: 20px;">
                        <button id="btRemoveChild">Remove Last Child</button>
                        <button id="btAddChild">Add Another Child</button>
                    </div>
               </div>
           </section>

           <section id="Parenting-Plan" style="display: none;">
               <div class="custodyVisitors contForm">
                   <h2>Custody & Visitation</h2>
                   <table cellpadding="0" cellspacing="0" width="100%">
                       <tr>
                           <td colspan="4">In Florida, parents are often granted Shared Parental Responsibility and Decision Making with one parent's residence designating the school district for the children. Alternatively, one parent can be granted Sole Parental Responsibility; the children can still have significant parenting time scheduled with the non-residential parent.</td>
                       </tr>
                        <tr>
                            <td colspan="4"><strong>Custody of the Children:</strong></td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-children" value="Shared Responsibility, Mother residence determines school district"></td>
                            <td width="90%" colspan="3">Shared Responsibility, <strong>Mother's</strong> residence determines school district</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-children" value="Shared Responsibility, Father residence determines school district"></td>
                            <td width="90%" colspan="3">Shared Responsibility,  <strong>Fathers's</strong> residence determines school district</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-children" value="Mothers has Sole Parental Responsibility"></td>
                            <td width="90%" colspan="3"><strong>Mother's</strong> has Sole Parental Responsibility</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-children" value="Fathers has Sole Parental Responsibility"></td>
                            <td width="90%" colspan="3"><strong>Fathers's</strong> has Sole Parental Responsibility</td>
                        </tr>
                        <tr><td colspan="4"><hr></td></tr>
                        <tr>
                            <td colspan="4"><strong>Weekend Parenting Time/Visitation</strong></td>
                        </tr>
                         <tr>
                            <td colspan="4">The non-residential parent shall have possesion of the children:</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-WeekendTime" value="No Weekend Visits Scheduled"></td>
                            <td width="90%" colspan="3">No Weekend Visits Scheduled</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-WeekendTime" value="The weekend of the first and third Friday of each month."></td>
                            <td width="90%" colspan="3">The weekend of the first and third Friday of each month.</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-WeekendTime" value="The weekend of the first, third, and fifth Friday of each month."></td>
                            <td width="90%" colspan="3">The weekend of the first, third, and fifth Friday of each month.</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-WeekendTime" value="The weekend of the second and fourth Friday of each month."></td>
                            <td width="90%" colspan="3">The weekend of the second and fourth Friday of each month.</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-WeekendTime" value="The weekend of the second and fourth Friday of each month."></td>
                            <td width="90%" colspan="3">Other: <input type="text" name="custody-WeekendTime-other" value=""></td>
                        </tr>
                        <tr>
                            <td width="24%" colspan="2">Vistation begins:</td>
                            <td width="20%"> <input type="text" name="custody-VistationBegins" value=""></td>
                            <td width="56%"> (day and time) ex. "Friday 5 p.m."</td>
                        </tr>
                        <tr>
                            <td width="24%" colspan="2">Visitation ends:</td>
                            <td width="20%"> <input type="text" name="custody-VistationEnds" value=""></td>
                            <td width="56%"> ex. "Sunday 5 p.m."</td>
                        </tr>
                        <tr>
                            <td colspan="4"><strong>Weekday Parenting Time</strong></td>
                        </tr>
                         <tr>
                            <td colspan="4">The non-residential parent shall have possession of the children:</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-WeekendParentingTime" value="No Weekday Visits Scheduled"></td>
                            <td width="90%" colspan="3">No Weekday Visits Scheduled</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-WeekendParentingTime" value="Every Wednesday Evening"></td>
                            <td width="90%" colspan="3">Every Wednesday Evening</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-WeekendParentingTime" value="Every other Wednesday Evening"></td>
                            <td width="90%" colspan="3">Every other Wednesday Evening</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-WeekendParentingTime" value="Other"></td>
                            <td width="90%" colspan="3">Other: <input type="text" name="custody-WeekendParentingTime-other" value=""></td>
                        </tr>
                        <tr>
                            <td width="24%" colspan="2">Vistation begins:</td>
                            <td width="20%"> <input type="text" name="custody-VistationParentingBegins" value=""></td>
                            <td width="56%"> (time) ex. "3 p.m."</td>
                        </tr>
                        <tr>
                            <td width="24%" colspan="2">Visitation ends:</td>
                            <td width="20%"> <input type="text" name="custody-VistationParentingEnds" value=""></td>
                            <td width="56%"> ex. "8 p.m."</td>
                        </tr>
                        <tr><td colspan="4"><hr></td></tr>
                        <tr>
                            <td colspan="4"><strong>Winter Break:</strong> from the last day of school in December until school resumes in January</td>
                        </tr>
                         <tr>
                            <td colspan="4">The non-residential parent shall have possession of the children:</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-WinterBreak" value="Same as Regular Weekend/Weekday Schedule"></td>
                            <td width="90%" colspan="3">Same as Regular Weekend/Weekday Schedule</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-WinterBreak" value="From / To"></td>
                            <td width="90%" colspan="3">From <input type="text" name="custody-WinterBreak-from"> (day and time)</td>
                        </tr>
                        <tr>
                            <td width="5%"></td>
                            <td width="90%" colspan="3">To <input type="text" name="custody-WinterBreak-To"> (day and time)</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-WinterBreak" value="Other"></td>
                            <td width="90%" colspan="3">Other: <input type="text" name="custody-WinterBreak-other" value=""></td>
                        </tr>
                        <tr><td colspan="4"><hr></td></tr>
                        <tr>
                            <td colspan="4"><strong>Spring Break:</strong> as scheduled by the school Calendar</td>
                        </tr>
                         <tr>
                            <td colspan="4">The non-residential parent shall have possession of the children:</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-SpringBreak" value="Same as Regular Weekend/Weekday Schedule"></td>
                            <td width="90%" colspan="3">Same as Regular Weekend/Weekday Schedule</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-SpringBreak" value="From / To"></td>
                            <td width="90%" colspan="3">From <input type="text" name="custody-SpringBreak-from"> (day and time)</td>
                        </tr>
                        <tr>
                            <td width="5%"></td>
                            <td width="90%" colspan="3">To <input type="text" name="custody-SpringBreak-To"> (day and time)</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-SpringBreak" value="Other"></td>
                            <td width="90%" colspan="3">Other: <input type="text" name="custody-SpringBreak-other" value=""></td>
                        </tr>
                        <tr><td colspan="4"><hr></td></tr>
                        <tr>
                            <td colspan="4"><strong>Summer</strong></td>
                        </tr>
                         <tr>
                            <td colspan="4">The non-residential parent shall have possession of the children:</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-SummerBreak" value="Same as Regular Weekend/Weekday Schedule"></td>
                            <td width="90%" colspan="3">Same as Regular Weekend/Weekday Schedule</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-SummerBreak" value="From / To"></td>
                            <td width="90%" colspan="3">From <input type="text" name="custody-SummerBreak-from"> (day and time)</td>
                        </tr>
                        <tr>
                            <td width="5%"></td>
                            <td width="90%" colspan="3">To <input type="text" name="custody-SummerBreak-To"> (day and time)</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-SummerBreak" value="Other"></td>
                            <td width="90%" colspan="3">Other: <input type="text" name="custody-SummerBreak-other" value=""></td>
                        </tr>
                    </table>
               </div>
               <div class="Holidays contForm">
                   <h2>Holidays</h2>

                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td colspan="4"><strong>Custody of the Children:</strong></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>New Years Day</strong></td>
                            <td width="20%"><input type="radio" name="custody-holidays-NewYear" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-NewYear" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-holidays-NewYear-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-NewYear-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-NewYear-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Martin Luther King Day</strong></td>
                            <td width="20%"><input type="radio" name="custody-holidays-MartinLutherKing" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-MartinLutherKing" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-holidays-MartinLutherKing-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-MartinLutherKing-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-MartinLutherKing-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Presidents' Day</strong></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Presidents" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Presidents" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-holidays-Presidents-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Presidents-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Presidents-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Memorial Day</strong></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Memorial" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Memorial" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-holidays-Memorial-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Memorial-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Memorial-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>July 4th</strong></td>
                            <td width="20%"><input type="radio" name="custody-holidays-July4" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-July4" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-holidays-July4-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-July4-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-July4-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Labor Day</strong></td>
                            <td width="20%"><input type="radio" name="custody-holidays-labor" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-labor" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-holidays-labor-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-labor-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-labor-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Veterans' Day</strong></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Veterans" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Veterans" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-holidays-Veterans-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Veterans-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Veterans-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Thanksgiving Day</strong></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Thanksgiving" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Thanksgiving" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-holidays-Thanksgiving-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Thanksgiving-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Thanksgiving-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Christmas Eve</strong></td>
                            <td width="20%"><input type="radio" name="custody-holidays-ChristmasEve" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-ChristmasEve" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-holidays-ChristmasEve-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-ChristmasEve-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-ChristmasEve-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Christmas Day</strong></td>
                            <td width="20%"><input type="radio" name="custody-holidays-ChristmasDay" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-ChristmasDay" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-holidays-ChristmasDay-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-ChristmasDay-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-ChristmasDay-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Additional Holiday 1</strong></td>
                            <td width="60%" colspan="3"><input type="text" name="custody-holidays-Additional1" value=""></td>
                        </tr>
                        <tr>
                            <td width="40%">Parent</td>
                            <td width="20%"><input type="radio" name="custody-holidays-Additional1-parent" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Additional1-parent" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-holidays-Additional1-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Additional1-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Additional1-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Additional Holiday 2</strong></td>
                            <td width="60%" colspan="3"><input type="text" name="custody-holidays-Additional2" value=""></td>
                        </tr>
                        <tr>
                            <td width="40%">Parent</td>
                            <td width="20%"><input type="radio" name="custody-holidays-Additional2-parent" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Additional2-parent" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-holidays-Additional2-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Additional2-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-Additional2-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr><td colspan="4"><hr></td></tr>
                        <tr>
                            <td colspan="2" width="60%">All holidays listed will begin:</td>
                            <td colspan="2" width="40%"><input type="text" name="custody-holidays-ListedBegin"></td>
                        </tr>
                        <tr>
                            <td colspan="2" width="60%">End:</td>
                            <td colspan="2" width="40%"><input type="text" name="custody-holidays-end"></td>
                        </tr>
                        <tr>
                            <td colspan="2" width="60%">Holidays that fall on a Friday or Monday will include Saturday and Sunday:</td>
                            <td width="20%"><input type="radio" name="custody-holidays-IncludeWeekEnd" value="Yes"> <label for="">Yes</label></td>
                            <td width="20%"><input type="radio" name="custody-holidays-IncludeWeekEnd" value="No"> <label for="">No</label></td>
                        </tr>
                    </table>
               </div>
               <div class="SpecialOccasions contForm">
                   <h2>Special Occasions</h2>

                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td colspan="4"><strong>Custody of the Children:</strong></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Jack's Birthday</strong></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-JackBith" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-JackBith" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-JackBith-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-JackBith-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-JackBith-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Mother's Birthday</strong></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-MotherBirth" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-MotherBirth" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-MotherBirth-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-MotherBirth-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-MotherBirth-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Father's Birthday</strong></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-FatherBirth" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-FatherBirth" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-FatherBirth-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-FatherBirth-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-FatherBirth-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Mother's Day</strong></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-MotherDay" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-MotherDay" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-MotherDay-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-MotherDay-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-MotherDay-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Father's Day</strong></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-FatherDay" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-FatherDay" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-FatherDay-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-FatherDay-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-FatherDay-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Other 1</strong></td>
                            <td width="60%" colspan="3"><input type="text" name="custody-SpecialOccasions-Other1" value=""></td>
                        </tr>
                        <tr>
                            <td width="40%">Parent</td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-Other1-parent" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-Other1-parent" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-Other1-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-Other1-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-Other1-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Other 2</strong></td>
                            <td width="60%" colspan="3"><input type="text" name="custody-SpecialOccasions-Other2" value=""></td>
                        </tr>
                        <tr>
                            <td width="40%">Parent</td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-Other2-parent" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-Other2-parent" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%">Year</td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-Other2-Year" value="Even"> <label for="">Even</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-Other2-Year" value="Odd"> <label for="">Odd</label></td>
                            <td width="20%"><input type="radio" name="custody-SpecialOccasions-Other2-Year" value="Every"> <label for="">Every</label></td>
                        </tr>
                    </table>
               </div>
               <div class="MajorDecisions contForm">
                   <h2>Major Decisions</h2>

                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td colspan="4">All major decisions regarding educational decisions, non-emergency health care, religious upbringing, and extracurricular activities will be made jointly by both parents. Should you be unable to reach consensus final decisions will be made as follows:</td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Education Decisions</strong></td>
                            <td width="20%"><input type="radio" name="custody-MajorDecisions-Education" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-MajorDecisions-Education" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Non-emergency health care</strong></td>
                            <td width="20%"><input type="radio" name="custody-MajorDecisions-HealthCare" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-MajorDecisions-HealthCare" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                        <tr>
                            <td width="40%"><strong>Religious Upbringing</strong></td>
                            <td width="20%"><input type="radio" name="custody-MajorDecisions-Religius" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-MajorDecisions-Religius" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>

                        <tr>
                            <td width="40%"><input type="text" name="custody-MajorDecisions-add1"></td>
                            <td width="20%"><input type="radio" name="custody-MajorDecisions-add1" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-MajorDecisions-add1" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>

                        <tr>
                            <td width="40%"><input type="text" name="custody-MajorDecisions-add2"></td>
                            <td width="20%"><input type="radio" name="custody-MajorDecisions-add2" value="Mother"> <label for="">Mother</label></td>
                            <td width="20%"><input type="radio" name="custody-MajorDecisions-add2" value="Father"> <label for="">Father</label></td>
                            <td width="20%"></td>
                        </tr>
                    </table>
               </div>
               <div class="IncomeTaxes contForm">
                   <h2>Income Tax Exemptions</h2>

                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td colspan="3">Who will claim the child(ren) as exemptions on tax returns?</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-IncomeTaxes-who" value="Mother Every Year"></td>
                            <td colspan="2">Mother Every Year</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-IncomeTaxes-who" value="Father Every Year"></td>
                            <td>Father Every Year</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-IncomeTaxes-who" value="Alternating Years (Mother Even Years)"></td>
                            <td colspan="2">Alternating Years (Mother Even Years)</td>
                        </tr>
                        <tr>
                            <td width="5%"><input type="radio" name="custody-IncomeTaxes-who" value="Alternating Years (Father Even Years)"></td>
                            <td colspan="2">Alternating Years (Father Even Years)</td>
                        </tr>
                        <tr><td colspan="3"><hr></td></tr>
                        <tr>
                            <td colspan="3">Based on your previous entries, estimate the percent of nights that the children will spend with each parent.</td>
                        </tr>
                        <tr>
                            <td colspan="2">Percent of Nights children spend with Mother (0-100)</td>
                            <td width="15%"><input type="number" name="custody-IncomeTaxes-percentMother" value="" style="max-width: 50px;" max="100"> %</td>
                        </tr>
                        <tr>
                            <td colspan="2">Percent of Nights children spend with Father (0-100)</td>
                            <td width="15%"><input type="number" name="custody-IncomeTaxes-percentFather" value="" style="max-width: 50px;" max="100"> %</td>
                        </tr>
                    </table>
               </div>
           </section>

           <section id="Property" style="display: none;">
               <div class="Property contForm">
                   <h2>Property</h2>
                   <table cellpadding="0" cellspacing="0" width="100%">
                       <tr>
                           <td colspan="4">Marital property consists of the property, other than separate property, acquired by either party during the marriage. Anything earned or acquired with marital money is owned equally by the Husband and Wife.</td>
                       </tr>
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2">Do you have cash on hand to divide (this is cash money that is NOT in any bank account)?</td>
                           <td width="20%"><input type="radio" name="Property-cash" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-cash" value="No"> <label for="">No</label></td>
                       </tr>
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Real Estate:</strong> Do you have any houses or land?</td>
                           <td width="20%"><input type="radio" name="Property-realEstate" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-realEstate" value="No"> <label for="">No</label></td>
                       </tr>
                   </table>                   
                   <table cellpadding="0" cellspacing="0" width="100%">
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Vehicles:</strong> Do you have any motor vehicles that need to be separated?</td>
                           <td width="20%"><input type="radio" name="Property-Vehicles" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-Vehicles" value="No"> <label for="">No</label></td>
                       </tr>
                    </table>
                    <table cellpadding="0" cellspacing="0" width="100%" id="vehicle">
                       <tr>
                           <td width="40%">Vehicle Description:</td>
                           <td width="60%" colspan="3"><textarea name="Property-VehicleDescription" cols="34"></textarea></td>
                       </tr>
                       <tr>
                           <td width="40%">Market Value:</td>
                           <td width="60%" colspan="3">$ <input type="number" name="Property-VehicleValue"></td>
                       </tr>
                       <tr>
                           <td width="40%">Whose name(s) are currently on the title?</td>
                           <td width="20%"><input type="radio" name="Property-VehicleTitular" value="Husband"> <label for="">Husband</label></td>
                           <td width="20%"><input type="radio" name="Property-VehicleTitular" value="Wife"> <label for="">Wife</label></td>
                           <td width="20%"><input type="radio" name="Property-VehicleTitular" value="Both"> <label for="">Both</label></td>
                       </tr>
                       <tr>
                           <td width="40%">Is there money owed on the vehicle?</td>
                           <td width="20%"><input type="radio" name="Property-VehicleOwed" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-VehicleOwed" value="No"> <label for="">No</label></td>
                           <td width="20%"></td>
                       </tr>
                       <tr>
                           <td width="40%">Who will keep this vehicle?</td>
                           <td width="20%"><input type="radio" name="Property-VehicleKeep" value="Husband"> <label for="">Husband</label></td>
                           <td width="20%"><input type="radio" name="Property-VehicleKeep" value="Wife"> <label for="">Wife</label></td>
                           <td width="20%"></td>
                       </tr>
                    </table>
                    <div id="duplicate-vehicle"></div>
                    <div class="buttons" style="padding-top: 20px;">
                        <button id="btRemoveVehicle">Remove Last Vehicle</button>
                        <button id="btAddVehicle">Add Another Vehicle</button>
                    </div>
                    <table cellpadding="0" cellspacing="0" width="100%">
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Retirement Benefits:</strong>  Do you have retirement plans to separate?</td>
                           <td width="20%"><input type="radio" name="Property-Retirement" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-Retirement" value="No"> <label for="">No</label></td>
                       </tr>
                    </table>                    
                    <table cellpadding="0" cellspacing="0" width="100%" id="plan">
                       <tr>
                           <td width="40%">Description including Plan Name:</td>
                           <td width="60%" colspan="3"><textarea name="Property-PlanName" cols="34"></textarea></td>
                       </tr>
                       <tr>
                           <td width="40%">Plan Administrator</td>
                           <td width="60%" colspan="3"><input type="text" name="Property-PlanAdministrator"></td>
                       </tr>
                       <tr>
                           <td width="40%">Market Value:</td>
                           <td width="60%" colspan="3">$ <input type="number" name="Property-PlanValue"></td>
                       </tr>
                       <tr>
                           <td width="40%">Who will keep this account?</td>
                           <td width="20%"><input type="radio" name="Property-PlanKeep" value="Husband"> <label for="">Husband</label></td>
                           <td width="20%"><input type="radio" name="Property-PlanKeep" value="Wife"> <label for="">Wife</label></td>
                           <td width="20%"><input type="radio" name="Property-PlanKeep" value="Divided"> <label for="">Divided</label></td>
                       </tr>
                    </table>
                    <div id="duplicate-plan"></div>
                    <div class="buttons" style="padding-top: 20px;">
                        <button id="btRemovePlan">Remove Last Plan</button>
                        <button id="btAddPlan">Add Another Plan</button>
                    </div>
                    <table cellpadding="0" cellspacing="0" width="100%">
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Bank Accounts: </strong>  Do you have bank accounts to divide?</td>
                           <td width="20%"><input type="radio" name="Property-BankAccount" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-BankAccount" value="No"> <label for="">No</label></td>
                       </tr>
                    </table>                    
                    <table cellpadding="0" cellspacing="0" width="100%" id="bankaccount">
                       <tr>
                           <td width="40%">Description including bank name and account type (do not enter account #)</td>
                           <td width="60%" colspan="3"><textarea name="Property-BankAccountDescription" cols="34"></textarea></td>
                       </tr>
                       <tr>
                           <td width="40%">Market Value:</td>
                           <td width="60%" colspan="3">$ <input type="number" name="Property-BankAccountValue"></td>
                       </tr>
                       <tr>
                           <td width="40%">Who will keep this account?</td>
                           <td width="20%"><input type="radio" name="Property-BankAccountKeep" value="Husband"> <label for="">Husband</label></td>
                           <td width="20%"><input type="radio" name="Property-BankAccountKeep" value="Wife"> <label for="">Wife</label></td>
                           <td width="20%"></td>
                       </tr>
                    </table>
                    <div id="duplicate-bankaccount"></div>
                    <div class="buttons" style="padding-top: 20px;">
                        <button id="btRemoveBankAccount">Remove Last Bank Account</button>
                        <button id="btAddBankAccount">Add Another Bank Account</button>
                    </div>
                    <table cellpadding="0" cellspacing="0" width="100%">
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Investment Accounts:</strong> Do you have investment accounts or stocks/bonds/mutual funds to divide?</td>
                           <td width="20%"><input type="radio" name="Property-InvestmentAccounts" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-InvestmentAccounts" value="No"> <label for="">No</label></td>
                       </tr>
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Life Insurance:</strong> Do you have life insurance that needs to be divided?</td>
                           <td width="20%"><input type="radio" name="Property-LifeInsurance" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-LifeInsurance" value="No"> <label for="">No</label></td>
                       </tr>
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Boats:</strong> Do you have any boats to divide?</td>
                           <td width="20%"><input type="radio" name="Property-Boats" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-Boats" value="No"> <label for="">No</label></td>
                       </tr>
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Other Vehicles: </strong>Do you have any other vehicles to divide?</td>
                           <td width="20%"><input type="radio" name="Property-OtherVehicles" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-OtherVehicles" value="No"> <label for="">No</label></td>
                       </tr>
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Owed Money:</strong> Do you have any money owed to you to divide?</td>
                           <td width="20%"><input type="radio" name="Property-OwedMoney" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-OwedMoney" value="No"> <label for="">No</label></td>
                       </tr>
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Furniture:</strong> Do you have any furniture to divide?</td>
                           <td width="20%"><input type="radio" name="Property-Furniture" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-Furniture" value="No"> <label for="">No</label></td>
                       </tr>
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Jewelry and Collectibles:</strong> Do you have any jewelry or collectibles to divide?</td>
                           <td width="20%"><input type="radio" name="Property-Jewelry" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-Jewelry" value="No"> <label for="">No</label></td>
                       </tr>
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Sports and Entertainment Equipment:</strong> Do you have any sports or entertainment equipment to divide?</td>
                           <td width="20%"><input type="radio" name="Property-Sports" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-Sports" value="No"> <label for="">No</label></td>
                       </tr>
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Business Interests:</strong> Do you have any business interests to divide?</td>
                           <td width="20%"><input type="radio" name="Property-Business" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-Business" value="No"> <label for="">No</label></td>
                       </tr>
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Additional Property:</strong> Do you have additional property to divide?</td>
                           <td width="20%"><input type="radio" name="Property-AdditionalProperty" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-AdditionalProperty" value="No"> <label for="">No</label></td>
                       </tr>
                        
                    </table>
               </div>
               <div class="debts contForm">
                   <h2>Debt</h2>
                   <table cellpadding="0" cellspacing="0" width="100%">
                       <tr>
                           <td colspan="4">Marital debt is like marital property. Any debts acquired between the marriage and date of separation are marital. Do not list real estate or vehicle debt that was already listed in the property portion of the interview.</td>
                       </tr>
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Credit Card Debt:</strong> Do you have Credit Card debt you need to divide?</td>
                           <td width="20%"><input type="radio" name="Property-debt-credit-car" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-debt-credit-car" value="No"> <label for="">No</label></td>
                       </tr>
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Bank Loans:</strong>  Do you have Bank/Credit Union Loans to divide?</td>
                           <td width="20%"><input type="radio" name="Property-debt-bankLoans" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-debt-bankLoans" value="No"> <label for="">No</label></td>
                       </tr>
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Judgments:</strong> Do you have Court Judgment Payments to divide?</td>
                           <td width="20%"><input type="radio" name="Property-debt-Judgments" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-debt-Judgments" value="No"> <label for="">No</label></td>
                       </tr>
                       <tr><td colspan="4"><hr></td></tr>
                       <tr>
                           <td width="60%" colspan="2"><strong>Other Debts:</strong> Do you have other debts to divide between you and your spouse?</td>
                           <td width="20%"><input type="radio" name="Property-debt-Other" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Property-debt-Other" value="No"> <label for="">No</label></td>
                       </tr>
                   </table>                    
                   <table cellpadding="0" cellspacing="0" width="100%" id="otherdebt">
                       <tr>
                           <td width="40%">Description including bank name and account type (do not enter account #)</td>
                           <td width="60%" colspan="3"><textarea name="Property-debtOtherDescription" cols="34"></textarea></td>
                       </tr>
                       <tr>
                           <td width="40%">Creditor:</td>
                           <td width="60%" colspan="3"><input type="text" name="Property-debtOtherCreditor"></td>
                       </tr>
                       <tr>
                           <td width="40%">Current Amount Owed:</td>
                           <td width="60%" colspan="3">$ <input type="number" name="Property-debtOtherAmount"></td>
                       </tr>
                       <tr>
                           <td width="40%">Monthly Payment:</td>
                           <td width="60%" colspan="3">$ <input type="number" name="Property-debtOtherMonthly"></td>
                       </tr>
                       <tr>
                           <td width="40%">Who will be responsible for this debt?</td>
                           <td width="20%"><input type="radio" name="Property-debtOtherResponsible" value="Husband"> <label for="">Husband</label></td>
                           <td width="20%"><input type="radio" name="Property-debtOtherResponsible" value="Wife"> <label for="">Wife</label></td>
                           <td width="20%"></td>
                       </tr>
                    </table>
                    <div id="duplicate-otherdebt"></div>
                    <div class="buttons" style="padding-top: 20px;">
                        <button id="btRemoveOtherDebt">Remove Last Bank Account</button>
                        <button id="btAddOtherDebt">Add Another Bank Account</button>
                    </div>      
               </div>
           </section>

           <section id="Child-Support" style="display: none;">

               <div class="Alimony contForm">
                   <h2>Spousal Support</h2>
                   <table cellpadding="0" cellspacing="0" width="100%">
                       <tr>
                           <td width="60%" colspan="2">Will there be spousal support?</td>
                           <td width="20%"><input type="radio" name="Support-spousalSupport" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="Support-spousalSupport" value="No"> <label for="">No</label></td>
                       </tr>
                       <tr>
                           <td width="60%" colspan="2">Which spouse will pay support?</td>
                           <td width="20%"><input type="radio" name="Support-PaySupport" value="Husband"> <label for="">Husband</label></td>
                           <td width="20%"><input type="radio" name="Support-PaySupport" value="Wife"> <label for="">Wife</label></td>
                       </tr>
                       <tr>
                           <td width="60%" colspan="2">Reason for Maintenance</td>
                           <td width="40%" colspan="2"><textarea name="Support-ReasonMaintenance" cols="34"></textarea></td>
                       </tr>
                       <tr>
                           <td width="60%" colspan="2">Monthly Amount</td>
                           <td width="40%" colspan="2">$<input type="number" name="Support-Monthly" value=""></td>
                       </tr>
                       <tr>
                           <td width="60%" colspan="2">Length of Payment</td>
                           <td width="40%" colspan="2"><input type="number" name="Support-Length" value=""> month</td>
                       </tr>
                       <tr>
                           <td width="60%" colspan="2">First Payment Date (MM/DD/YYYY)</td>
                           <td width="40%" colspan="2"><input type="date" name="Support-Length" value=""></td>
                       </tr>
                   </table>
               </div>

               <div class="ChildSupport contForm">
                   <h2>Child Support</h2>
                   <table cellpadding="0" cellspacing="0" width="100%">
                       <tr>
                           <td colspan="3">Based upon the the number of children (1) and monthly income, the following monthly payments would be required of the spouse who is selected to pay child support. This calculation takes into account that the children spend at least 20% of the nights with each parent.</td>
                       </tr>
                        <tr>
                            <td width="70%"></td>
                            <td width="15%">Mother</td>
                            <td width="15%">Father</td>
                        </tr>
                        <!-- ESTO ES LA FORMULA / CÁLCULO -->
                        <tr>
                            <td width="70%">Monthly Net Income</td>
                            <td width="15%">$2,400.00</td>
                            <td width="15%">-$1,400.00</td>
                        </tr>
                        <tr>
                            <td width="70%">Monthly Child Support Obligation</td>
                            <td width="15%">$400.00</td>
                            <td width="15%">$140.00</td>
                        </tr>
                        <tr>
                            <td width="70%">Monthly Child Support Credits</td>
                            <td width="15%">$0.00</td>
                            <td width="15%">$0.00</td>
                        </tr>
                        <tr>
                            <td width="70%"><strong>Monthly Payment (Standard Calculation)</strong></td>
                            <td width="15%"><strong>$330.00</strong></td>
                            <td width="15%"><strong>$0.00</strong></td>
                        </tr>
                        <!-- /ESTO ES LA FORMULA / CÁLCULO -->
                        <tr>
                            <td width="70%">Will you be using the above payment calculation?</td>
                            <td width="15%"><input type="radio" name="ChildSupport-Using" value="Yes"> <label>Yes</label></td>
                            <td width="15%"><input type="radio" name="ChildSupport-Using" value="No"> <label>No</label></td>
                        </tr>
                        <tr>
                            <td width="70%">First Payment Date (MM/DD/YYYY)</td>
                            <td width="30%" colspan="2">
                                <input type="date" name="ChildSupport-FirstPayment" value="">
                            </td>
                        </tr>
                        <tr>
                            <td width="70%">Day of the month payment will be made</td>
                            <td width="30%" colspan="2">
                                <select size="1" name="ChildSupport-DayOfMonth">
                                    <option selected>Select Day</option>
                                    <option>1st</option>
                                    <option>2nd</option>
                                    <option>3rd</option>
                                    <option>4th</option>
                                    <option>5th</option>
                                    <option>6th</option>
                                    <option>7th</option>
                                    <option>8th</option>
                                    <option>9th</option>
                                    <option>10th</option>
                                    <option>11th</option>
                                    <option>12th</option>
                                    <option>13th</option>
                                    <option>14th</option>
                                    <option>15th</option>
                                    <option>16th</option>
                                    <option>17th</option>
                                    <option>18th</option>
                                    <option>19th</option>
                                    <option>20th</option>
                                    <option>21st</option>
                                    <option>22nd</option>
                                    <option>23rd</option>
                                    <option>24th</option>
                                    <option>25th</option>
                                    <option>26th</option>
                                    <option>27th</option>
                                    <option>28th</option>
                                    <option>29th</option>
                                    <option>30th</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td width="70%">Will child support payments be made directly to the person or through the Florida county's Central Governmental Depository (service charge may apply)?</td>
                            <td width="15%"><input type="radio" name="ChildSupport-DirectyCounty" value="Direct"> <label>Direct</label></td>
                            <td width="15%"><input type="radio" name="ChildSupport-DirectyCounty" value="County"> <label>County</label></td>
                        </tr>
                        <tr>
                            <td width="70%">Which parent will be paying for the Health Insurance of the children?</td>
                            <td width="15%"><input type="radio" name="ChildSupport-PayHealth" value="Mother"> <label>Mother</label></td>
                            <td width="15%"><input type="radio" name="ChildSupport-PayHealth" value="Father"> <label>Father</label></td>
                        </tr>

                    </table>
               </div>
           </section>

           <section id="Name-Change" style="display: none;">
               <div class="NameChange contForm">
                   <h2>Name Change</h2>

                   <table cellpadding="0" cellspacing="0" width="100%">
                       <tr>
                           <td colspan="4">If the Wife changed her name when the parties married, she can change it back to her maiden or other former name.</td>
                       </tr>
                       <tr>
                           <td width="60%" colspan="2">Does Wife want a name change?</td>
                           <td width="20%"><input type="radio" name="NameChange" value="Yes"> <label for="">Yes</label></td>
                           <td width="20%"><input type="radio" name="NameChange" value="No"> <label for="">No</label></td>
                       </tr>
                   </table>
               </div>
           </section>
       </main>
   </div>
   <div class="containerForm">
       
       <footer>
           Please review each of the pages in the interview and provide any additional information needed for your Florida documents. Upon completing the online interview, you will be able to request your documents be shipped to you. Use the Navigation Pane on the left to jump to any section of the interview at any time.
       </footer>
   </div>
    </section>
</main>


<script>

    //duplicator Child
    let i = 0
    $('#btAddChild').on('click', function(){
        i++
        let clone = $('#child').clone()
        $('#duplicate-child').prepend(clone.attr('id','child'+i))
    })
    $('#btRemoveChild').on('click', function(){
        if(i > 0){
            $('#child'+i).remove()
            i--
        }
    })

    //duplicator Vehicle
    let v = 0
    $('#btAddVehicle').on('click', function(){
        v++
        let clone = $('#vehicle').clone()
        $('#duplicate-vehicle').prepend(clone.attr('id','vehicle'+v))
    })
    $('#btRemoveVehicle').on('click', function(){
        if(v > 0){
            $('#vehicle'+v).remove()
            v--
        }
    })

    //duplicator Plan
    let p = 0
    $('#btAddPlan').on('click', function(){
        p++
        let clone = $('#plan').clone()
        $('#duplicate-plan').prepend(clone.attr('id','plan'+p))
    })
    $('#btRemovePlan').on('click', function(){
        if(p > 0){
            $('#plan'+p).remove()
            p--
        }
    })

    //duplicator Bank Account
    let b = 0
    $('#btAddBankAccount').on('click', function(){
        b++
        let clone = $('#bankaccount').clone()
        $('#duplicate-bankaccount').prepend(clone.attr('id','bankaccount'+b))
    })
    $('#btRemoveBankAccount').on('click', function(){
        if(b > 0){
            $('#bankaccount'+b).remove()
            b--
        }
    })

    //duplicator Debt
    let d = 0
    $('#btAddOtherDebt').on('click', function(){
        d++
        let clone = $('#otherdebt').clone()
        $('#duplicate-otherdebt').prepend(clone.attr('id','otherdebt'+d))
    })
    $('#btRemoveOtherDebt').on('click', function(){
        if(d > 0){
            $('#otherdebt'+d).remove()
            d--
        }
    })

    //Navigator
    $('#navform li').on('click', function(){
        $('#navform li').removeClass('active')
        let data = $(this).data('section');
        $('.containerForm section').hide()
        $('.containerForm section#'+data).show()

        $(this).addClass('active')
    })
</script>



