
<div class="row wrapper">
    <div class="col-lg-10">
        <h2>Usuarios Administrador</h2>        
    </div>
    <div class="col-lg-2"></div>
</div>


<div class="row wrapper wrapper-content">  
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="row">
                
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Editar Usuario</h5>
                        </div>
                        <form class="form-horizontal" id="cargar_noticia" action="" method="POST" role="form">
                        <input type="hidden" name="envio01" value="1" />
                        <input type="hidden" name="_csrf" value="<?=$this->_sess->get('_csrf')?>">


                        
                        
                        
                        <div class="ibox-content">                           
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Nombre y Apellido</label>
                                <div class="col-lg-9">
                                  <input class="form-control" type="text" name="usuario_nombre" id="usuario_nombre" value="<?php echo $this->usuario->nombre?>">
                                </div>
                            </div>
                        </div>

                        

                        <div class="ibox-content">                           
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Email</label>
                                <div class="col-lg-9">
                                   <input class="form-control" type="text" name="usuario_email" id="usuario_email" value="<?php echo $this->usuario->email?>">
                                </div>
                            </div>
                        </div>

                       <div class="ibox-content">                           
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Usuario</label>
                                <div class="col-lg-9">
                                  <input class="form-control" type="text" name="usuario_usuario" id="usuario_usuario" value="<?php echo $this->usuario->usuario?>">
                                </div>
                            </div>
                        </div>

                        <div class="ibox-content">                           
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Password</label>
                                <div class="col-lg-9">
                                  <input class="form-control" type="password" name="usuario_pass" id="usuario_pass" placeholder="Si no coloca un nuevo Password, se conservara el actual.">
                                </div>
                            </div>
                        </div>
                      
                      <div class="ibox-content">                           
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Confirmar Password</label>
                                <div class="col-lg-9">
                                  <input class="form-control" type="password" name="usuario_repetir_pass" id="usuario_repetir_pass" value="" placeholder="Confirmar Password.">
                                </div>
                            </div>
                        </div>

                        <div class="ibox-content">                           
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Rol</label>
                                <div class="col-lg-9">
                                  <select class="form-control" name="usuario_rol" id="usuario_rol">
                                    <?php foreach($this->roles as $roles):?>
                                      <?php if($roles->id_role == $this->usuario->role):?>
                                      <option value="<?php echo $roles->id_role?>" selected><?php echo $roles->role?></option>
                                      <?php else:?>
                                      <option value="<?php echo $roles->id_role?>"><?php echo $roles->role?></option>
                                      <?php endif?>
                                      
                                      <?php endforeach?>
                                  </select>
                                </div>
                            </div>
                        </div>

                        

                     <!--    <div id="cont_gestion" class="ibox-content">                           
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Provincias a gestionar</label>
                                <div class="col-lg-9">
                                  <select class="form-control provs multipleSelect" multiple name="prov_gestion[]">
                                    <?php foreach($this->provincias as $prov):?>
                                    <?php if(in_array($prov->id, $this->prov_select)):?>
                                    <option value="<?=$prov->id?>" selected><?=$prov->nombre?></option> 
                                    <?php else:?>
                                    <option value="<?=$prov->id?>"><?=$prov->nombre?></option>
                                    <?php endif?>
                                    <?php endforeach?>                      
                                    </select>
                                </div>
                            </div>
                        </div> -->

                        <div class="ibox-content">
                          <div class="row">
                                <div class="form-group">
                                    <div class="col-lg-offset-2 col-lg-2">
                                      <input type="submit" class="btn btn-success" id="validatex" name="cargar" value="Guardar" />
                                    </div>                                                                       
                                </div>
                                
                             
                            </div>                            
                        </div>
                       </form> 
                    </div>
                </div>
          </div>
      </div>
  </div>
</div>





<!-- 

<div id="head-bg-fix"></div>
    <div class="wpContent">   
      <div class="btn-group-usuario">
          <a href="<?php echo $this->_conf['base_url'] . 'administrador/usuarios'?>">
            Administrar Usuario
          </a>

          <a href="<?php echo $this->_conf['base_url'] . 'administrador/usuarios/cargar'?>">
            Cargar Usuario
          </a>

          <a href="#" class="active">
            Editar Usuario
          </a>
      </div> 
  <div class="wpFormNewUser">
        
        	<form class="form-horizontal" id="cargar_noticia" action="" method="POST" role="form">
            <input type="hidden" name="envio01" value="1" />
            <input type="hidden" name="_csrf" value="<?=$this->_sess->get('_csrf')?>">
            
    			<legend>Editar Usuario</legend>
            	
            <div class=" <?php if(isset($this->errorNombre)) echo $this->errorNombre?>">
          			<label for="Categoria" class="labelInput">Nombre y Apellido</label>
      				<div class="wpFormInput">
                    	<input type="text" name="usuario_nombre" id="usuario_nombre" value="<?php echo $this->usuario->nombre?>">
                   	</div>
            	</div>
                
            <div class=" <?php if(isset($this->errorUsuario)) echo $this->errorUsuario?>">
          			<label for="Categoria" class="labelInput">Usuario</label>
      				<div class="wpFormInput">
                    	<input type="text" name="usuario_usuario" id="usuario_usuario" value="<?php echo $this->usuario->usuario?>">
                   	</div>
            	</div>
                
            <div class=" <?php if(isset($this->errorEmail)) echo $this->errorEmail?>">
          			<label for="Categoria" class="labelInput">Email</label>
      				<div class="wpFormInput">
                    	<input type="text" name="usuario_email" id="usuario_email" value="<?php echo $this->usuario->email?>">
                   	</div>
            	</div>
                
            <div class=" <?php if(isset($this->errorPass)) echo $this->errorPass?>">
          			<label for="Categoria" class="labelInput">Password</label>
      				<div class="wpFormInput">
                    	<input type="password" name="usuario_pass" id="usuario_pass" placeholder="Si no coloca un nuevo Password, se conservara el actual.">
                   	</div>
            	</div>
                
            <div class=" <?php if(isset($this->errorPassRepetir)) echo $this->errorPassRepetir?>">
          			<label for="Categoria" class="labelInput">Confirmar</label>
      				<div class="wpFormInput">
                    	<input type="password" name="usuario_repetir_pass" id="usuario_repetir_pass" value="" placeholder="Confirmar Password.">
                   	</div>
            	</div>
               
               
              <div class="">
            		<label for="Categoria" class="labelInput">Rol</label>
        				<div class="wpFormInput select">
                  	<select name="usuario_rol" id="usuario_rol">
                      	<?php foreach($this->roles as $roles):?>
                          <?php if($roles->id_role == $this->usuario->role):?>
                          <option value="<?php echo $roles->id_role?>" selected><?php echo $roles->role?></option>
                          <?php else:?>
                          <option value="<?php echo $roles->id_role?>"><?php echo $roles->role?></option>
                          <?php endif?>
                        	
                          <?php endforeach?>
                      </select>
                 	</div>
          		</div>
                
            
      <div id="cont_gestion">

        <div class=" <?php if(isset($this->errorProv)) echo $this->errorProv?>">
          <label for="prov_gestion" class="labelInput">Provincias a gestionar</label>

          <div class="wpProvs">

            <select class="provs multipleSelect" multiple name="prov_gestion[]">
            <?php foreach($this->provincias as $prov):?>
            <?php if(in_array($prov->id, $this->prov_select)):?>
            <option value="<?=$prov->id?>" selected><?=$prov->nombre?></option> 
            <?php else:?>
            <option value="<?=$prov->id?>"><?=$prov->nombre?></option>
            <?php endif?>
            <?php endforeach?>                      
            </select>

           
          </div>

        </div>

      </div>

      <div class="btnNewUser">

        <input type="submit" class="btn" id="validatex" name="cargar" value="Cargar Usuario" />

        <a class="btn btn-warning text-right btn-lg" style="margin-left: 20px;" href="<?php echo $this->_conf['base_url'] . 'administrador/usuarios/listar'?>">Cancelar</a>
   
      </div>

    </form>
  </div>  
</div> -->