<script src="https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js"></script>
<script>
$(document).ready(function() {


  /*$('.i-checks').iCheck({
      checkboxClass: 'icheckbox_square-green',
      radioClass: 'iradio_square-green',
  });*/


  $('#_enviar_data').click(function(){
       
      for (instance in CKEDITOR.instances) {
            CKEDITOR.instances[instance].updateElement();
        }
        
       
     if ($("#titulo").val() == "") {
      alert("You must complete the title field");
      $("#titulo").val('');
      $('#titulo').focus();     
      //$("#titulo").attr('placeholder', 'Titulo');
      return false;        
    }

    
    if ($("#precio").val() == "") {
      alert("You must complete the price field");
      $("#precio").val('');
      $('#precio').focus();     
      //$("#titulo").attr('placeholder', 'Titulo');
      return false;        
    }


        
     
     $("._loading").show();
     
     

       $.ajax({
            type: "POST",
            url: _root_ + "administrador/productos/consolidarCargarVariables",
            data: $("#cargar_trabajo").serialize(),
            success: function(data){
                $("._respuesta").html('').append(data).fadeIn('slow');
                $("._loading").hide();
            }
        });
        return false;
  });

  
    
  /*$('#cargar_trabajo').submit(function(){
    
    
    if ($("#titulo").val() == "") {
      alert("You must complete the title field");
      $("#titulo").val('');
      $('#titulo').focus();     
      //$("#titulo").attr('placeholder', 'Titulo');
      return false;        
    }

    
    if ($("#precio").val() == "") {
      alert("You must complete the price field");
      $("#precio").val('');
      $('#precio').focus();     
      //$("#titulo").attr('placeholder', 'Titulo');
      return false;        
    }
      
      return true;
    
  
  });*/
  
  
  
});

</script>


<div class="row wrapper">
    <div class="col-lg-10">
        <h2>Variable Products</h2>        
    </div>
    <div class="col-lg-2"></div>
</div>


<div class="row wrapper wrapper-content">  
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="row">
                
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Add</h5>
                        </div>
                        <form class="form-horizontal" id="cargar_trabajo" action="" method="POST" role="form" >
                          <input type="hidden" name="envio01" value="1" />
                          <input type="hidden" name="_csrf" value="<?=$this->_sess->get('_csrf')?>">
                          <input type="hidden" name="_tipo" value="interna">

                         <!--  <div class="ibox-content">
                            <div class="form-group">
                              <label for="num_referencia" class="col-lg-2 control-label">Estado</label>
                                <div class="col-lg-9">
                                  <select class="form-control" name="estado">
                                      <option value="alta">Alta</option>
                                        <option value="baja">Baja</option>
                                    </select>
                                </div>
                              </div>
                          </div> -->

                          

                          <div class="ibox-content">                           
                              <div class="form-group">
                                  <label class="col-lg-2 control-label">Title</label>
                                  <div class="col-lg-9">
                                     <input type="text" class="form-control" id="titulo" name="titulo" placeholder="Title" >
                                  </div>
                              </div>
                          </div>

                          <div class="ibox-content">
                            <div class="form-group">
                              <label class="col-lg-2 control-label">Description</label>
                              <div class="col-lg-9">
                                <textarea class="form-control" id="desc" name="desc"></textarea>
                                  <script>
                                      CKEDITOR.replace('desc', {
                                        language: 'en',
                                          extraPlugins: 'colorbutton',
                                          allowedContent: true,
                                      });
                                  </script>                              
                                 
                              </div>
                            </div>
                          </div>

                          <div class="ibox-content">
                            <div class="form-group">
                            <label for="precio" class="col-lg-2 control-label">Price</label>
                              <div class="col-lg-9 input-group"> 
                                <div class="input-group-addon">$</div>
                                <input class="form-control" id="precio" name="precio" placeholder="Price" type="text"  /> 
                              </div>  
                              </div>                            
                          </div>

                          


                          <!-- <div class="ibox-content">
                            <div class="form-group">
                            <label for="cantidad" class="col-lg-2 control-label">Cantidad</label>
                              <div class="col-lg-9 ">                                         
                                <input class="form-control" id="cantidad" name="cantidad" placeholder="Cantidad" type="number" />
                              </div>
                            </div>
                          </div>-->
 

                          

                          

                         <!--  <div class="ibox-content">
                            <div class="form-group">
                              <label for="contenido" class="col-lg-2 control-label">Imagen Principal</label>
                                <div class="col-lg-9">
                                    <div class="col-lg-5">
                                        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#_car_imgg_medidas">
                                            Cargar Imagen
                                        </button>
                                    </div>
                                    <div class="col-lg-7">
                                      <div class="list-group aa conexion _load_img_final_medidas" id="bloque_imgs_usuario">
                                        <?php $_img = admin::traerImg($this->_sess->get('carga_actual'),'cursos','principal');?>
                                        <?php if($_img !=''):?>
                                        <div><img src=" <?= $this->_conf['base_url'] . "public/img/subidas/cursos/principal/thumb/" . $_img->path ?>"  class="img-thumbnail"></div>
                                        <?php endif?>
                                        </div>
                                    </div>
                                </div>
                                </div>                  
                          </div>  -->


                            <!-- SEO -->

                        <div class="ibox-title" style="background-color: #d1e9ee;">
                            
                                <h5 class="col-lg-2" style="text-align: right;">SEO</h5>
                           
                        </div>

                        <div class="ibox-content">                           
                            <div class="form-group">
                                <label class="col-lg-2 control-label"><small>Title <code>title</code></small></label>
                                <div class="col-lg-9">
                                    <input type="text" placeholder="Title" class="form-control" name="titulo_seo" id="titulo_seo" maxlength="65">
                                </div>
                            </div>
                        </div>
                        
                        <div class="ibox-content">                           
                            <div class="form-group">
                                <label class="col-lg-2 control-label"><small>Description <code>meta-description</code></small></label>
                                <div class="col-lg-9">
                                    <textarea class="form-control" name="desc_seo" id="desc_seo" maxlength="10"></textarea>
                                    <script>
                                        CKEDITOR.plugins.addExternal( 'wordcount', '/libs/ckeditor/plugins/wordcount/', 'plugin.js' );
                                        CKEDITOR.replace('desc_seo', {
                                            language: 'en',
                                            allowedContent: true,
                                            extraPlugins: 'colorbutton,wordcount',
                                            height: 250,
                                             wordcount: {
                                                showCharCount: true,
                                                showWordCount: false,
                                                showParagraphs: false,
                                                countHTML: true,
                                                maxCharCount: -1,
                                                maxCharCount: 156,
                                            }
                                        } );
                                    </script>
                                </div>
                            </div>
                        </div>



                        <div class="ibox-content">
                            <div class="form-group">
                              <label for="contenido" class="col-lg-2 control-label">OG:image</label>
                                <div class="col-lg-9">
                                    <div class="col-lg-5">
                                        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#_car_img_seo">
                                            Add Image
                                        </button>
                                    </div>
                                    <div class="col-lg-7">
                                      <div class="list-group aa conexion _load_img_final_seo" id="bloque_imgs_seo">
                                        <?php $_img = admin::traerImg($this->_sess->get('carga_actual'),'seo');?>
                                        <?php if($_img !=''):?>
                                        <div>
                                            <img src="<?= $this->_conf['base_url'] . "public/img/subidas/seo/thumb/" . $_img->path ?>"  class="img-thumbnail">
                                            <input type="hidden" name="_seo_img" value="<?=$_img->id?>">
                                        </div>
                                        <?php endif?>
                                        </div>
                                    </div>
                                </div>
                                </div>                  
                          </div> 
                         

                          <!-- <div class="ibox-content">
                            <div class="row">
                                  <div class="form-group">
                                      <div class="col-lg-offset-2 col-lg-2">
                                        <input type="submit" class="btn btn-success" id="validatex" name="cargar" value="Save" />
                                      </div>                                                                       
                                  </div>
                              </div>                            
                          </div> -->

                          <div class="ibox-content">
                            <div class="row">
                                  <div class="form-group">
                                      <div class="col-lg-offset-2 col-lg-2">
                                          <button type="submit" id="_enviar_data" class="btn btn-success">Save</button>
                                          <button class="btn btn-white _loading" style="display:none;">
                                              <i class="fa fa-cog fa-spin fa-lg"></i>
                                          </button>
                                      </div>                                                                       
                                  </div>
                                  
                                  <div class="form-group">
                                      <div class="col-lg-offset-2 col-lg-9">
                                          <div class="_respuesta" style="display:none;color:red;"></div>
                                      </div>
                                  </div>
                              </div>                            
                          </div>



                        </form> 
                    </div>
                </div>
          </div>
      </div>
  </div>
</div>


<div class="modal inmodal fade" id="_car_img_seo" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <i class="fa fa-laptop modal-icon"></i>
                <h4 class="modal-title">Add Image</h4>
            </div>
            <div class="modal-body">
      <script>
          Dropzone.options.myAwesomeDropzoneSeo = {
            autoProcessQueue: false,
            paramName: 'file',
            parallelUploads: 1,
            maxFiles: 1,
            maxFilesize: <?=$this->_conf['peso_maximo_imagenes']?>, //MB
            dictDefaultMessage: 'Drag here to add, or click to select',
            acceptedFiles: 'image/*',
           
            init: function() {
      
              var myDropzone = this;
              var maxImageWidth = <?=$this->_conf['formatos_img']['seo_grandes']['ancho']?>, 
                  maxImageHeight = <?=$this->_conf['formatos_img']['seo_grandes']['alto']?>,
                  maxImagesize = <?=$this->_conf['peso_maximo_imagenes']?>;
      
              myDropzone.on("addedfile", function(file) {
                file.previewElement.addEventListener("click", function() { myDropzone.removeFile(file);});
              });
      
              this.element.querySelector("button[type=submit]").addEventListener("click", function(e) {
                e.preventDefault();
                e.stopPropagation();                                
                myDropzone.processQueue();
              });
      
              this.on('thumbnail', function(file) {

                if (file.width < maxImageWidth || file.height < maxImageHeight) {
                  // file.rejectDimensions();
                  this.removeFile(file);
                  alert("The image must be "+maxImageWidth+"x"+maxImageHeight+"px");
                  return false;
                }
              
              });
              
              this.on("queuecomplete", function(file) {this.removeAllFiles(file);img_final_seo('cargar','seo');});
              this.on("maxfilesexceeded", function(file){this.removeFile(file);});
              // this.on("error", function(file) {alert(file)});
              //this.on("complete", function(file) {this.removeAllFiles(file);});
              this.on("error", function(file) {
                //alert(file);
                if (file.width < maxImageWidth || file.height < maxImageHeight) {
                  //file.rejectDimensions();
                  this.removeFile(file);
                  alert("The image must be "+maxImageWidth+"x"+maxImageHeight+"px");
                  return false;
                }
                /*if(file.size > 1024*1024*2){
                  //2MB
                  this.removeFile(file);
                  alert("El peso de la imagen no puede superar los "+maxImagesize+"MB");
                  return false;
                }*/
              });
            }
          };
               
                      
        
      
        
         function img_final_seo(_accion, _tipo){
                    var url= _root_ + "administrador/imagenes/traerImagenfinal/"+_accion+"/"+_tipo;
                    $.ajax({
                        url:url,
                        contentType:"application/x-www-form-urlencoded",
                        dataType:"html",
                        error:function(){
                            //$("._load_img_final_logo").html("La conexion se ha perdido. <a href='" + _root_ + "administrador/imagenes'>Reinicie el proceso.</a>");
                        },
            
                        ifModified:false,
                        processData:true,
                        success:function(datas){
                            $("._load_img_final_seo").html(datas).fadeIn("slow");
                             $('#_car_img_seo').modal('hide');
                        },
                        type:"POST"
                    });
                }
        
        
                </script>
                <div class="loader"></div>
                <div id="contenedor">
            
                    <form class="form-inline dropzone" id="my-awesome-dropzone-seo" action="<?=$this->_conf['base_url']?>administrador/imagenes/cargImg/seo">
                        <input type="hidden" name="envio_img_princip" value="1">
                        <div class="dropzone-previews"></div>
                        <button type="submit" class="btn btn-primary pull-right">Add</button>
                    </form>
                    <p class="eliminarThumb">Click on the thumbnail to delete it.</p>
                    
                     <hr> 
                     
                    <div class="row">
                        <div class="col-lg-12">
                            <p class="text-danger"> 
                              <small>Image Size: <strong><?=$this->_conf['formatos_img']['seo_grandes']['ancho']?> x <?=$this->_conf['formatos_img']['seo_grandes']['alto']?> px</strong></small>
                              <br>
                              <small>Image max weight: <strong><?=$this->_conf['peso_maximo_imagenes']?> Mb.</strong></small>   
                          </p>
                        </div>
                    </div>
                    
                  
                    
                </div>
          </div>  
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">close</button>
            </div>        
      </div>
    </div>
</div>