<!-- <h2>Registro</h2>

<div class="well span5">
    <form name="form1" method="post" action="" class="form">
        <input type="hidden" value="1" name="enviar" />

        <p>
            <label>Nombre: </label>
            <input type="text" name="nombre" value="<?php if(isset($this->datos['nombre'])) echo $this->datos['nombre']?>" />
        </p>

        <p>
            <label>Usuario: </label>
            <input type="text" name="usuario" value="<?php if(isset($this->datos['usuario'])) echo $this->datos['usuario']?>" />
        </p>

        <p>
            <label>Email: </label>
            <input type="text" name="email" value="<?php if(isset($this->datos['email'])) echo $this->datos['email']?>" />
        </p>

        <p>
            <label>Password: </label>
            <input type="password" name="pass" />
        </p>

        <p>
            <label>Confirmar: </label>
            <input type="password" name="confirmar" />
        </p>    

        <p>
            <button type="submit" class="btn btn-primary">Enviar</button>
        </p>
    </form>
</div> -->