<main>
    <div class="how-works__header"><h3>HOW IT WORKS</h3></div>
    <section class="how-works">           

        <div class="container">

            <?=($this->data['texto']) ? $this->data['texto'] : ''?>
            <!-- <p>
                It works quickly, efficiently and inexpensively in three easy steps.
            </p>
            <ol>
                <li>Verify that you qualify.</li>
                <li>Select and purchase your package</li>
                <li>Complete your forms and have them electronically filed for you.</li>
            </ol>
            <p>
                TheQuickDivorce.com enables couples to access the appropriate legal forms and customized support needed to cost-efficiently finalize separations, custody arrangements, and divorces without having to hire lawyers.
            </p>
            <p>
                It is the one-stop digital destination for a unique, seamless solution to help couples avoid the standard separation and divorce process which can drain their time, energy and money. Conceptualized and launched by a noted family law attorney, divorced parent and author on family friendly divorce, TheQuickDivorce.com is distinguished as Florida’s low-cost, do-it-yourself divorce solution enabling couples to minimize the costs of separation and divorce while maximizing their peace of mind.
            </p>
            <p>
                Here’s how it works: Based on your responses to a series of questions, the team at TheQuickDivorce.com provides you with customized packets that include the specific forms you need to efficiently and effectively finalize your separation, custody arrangements and/or divorce.
            </p>
            <p>
                For an additional fee, you have the option of speaking with a staff member who can assist you with completing the forms (legal advice is not provided). The completed forms on your behalf! It’s that simple.
            </p>

            <p>
                If you get stuck, Thequickdivorce.com offers affordable mediation packages to help you come together on any issue.
            </p> -->

            <a href="<?=$this->_conf['base_url']?>getstarted" class="button"><p><strong>GET STARTED NOW</strong></p></a>
        </div>
    </section>
</main>