<main>
    <div class="how-works__header"><h3>TERMS AND CONDITIONS</h3></div>
    <section class="how-works">           

        <div class="container">

            <?=($this->data['texto']) ? $this->data['texto'] : ''?>
          
            <!-- <a href="<?=$this->_conf['base_url']?>getstarted" class="button"><p><strong>GET STARTED NOW</strong></p></a> -->
        </div>
    </section>
</main>