<div class="row">
	<div class="col-lg-6 col-lg-offset-2">
    	<h2>Nuevo Permiso</h2><br>
    </div>
</div>

<div class="row">
	<div class="col-lg-6 col-lg-offset-2">
    	<form class="form-horizontal" role="form" name="form1" method="post" action="">
 			<input type="hidden" name="guardar" value="1">
         		<div class="form-group <?php if(isset($this->errorCopete)) echo $this->errorCopete?>">
                <label for="permiso" class="col-lg-2 control-label">Permiso</label>
                <div class="col-lg-10">
                  <input type="text" class="form-control" id="permiso" name="permiso" placeholder="Permiso" value="<?php if(isset($this->datos['permiso'])) echo $this->datos['permiso']?>">
                </div>
              </div>
              <div class="form-group <?php if(isset($this->errorKey)) echo $this->errorKey?>">
                <label for="key" class="col-lg-2 control-label">Key</label>
                <div class="col-lg-10">
                  <input type="text" class="form-control" id="key" name="key" placeholder="Key" value="<?php if(isset($this->datos['key'])) echo $this->datos['key']?>">
                </div>
              </div>
              
              <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                  <button type="submit" class="btn btn-default">Guardar</button>
                </div>
              </div>
  		</form>
    </div>
</div>