<h2>Administración de permisos</h2>
<?php if(isset($this->permisos) && $this->permisos):?>
<table class="table table-bordered table-condensed table-striped" style="width:500px;">
    <tr>
        <th>ID</th>
        <th>Permiso</th>
        <th>Llave</th>
        <th colspan="2" class="text-center">Acci&oacute;n</th>
    </tr>

    <?php foreach($this->permisos as $permi):?>
    <tr>
		<td><?php echo $permi->id_permiso?></td>
    	<td><?php echo $permi->permiso?></td>
   	    <td><?php echo $permi->key?></td>
		<td><a data-toggle="modal" href="#editar_<?php echo $permi->id_permiso?>">Editar</a></td>
        <td><a data-toggle="modal" href="#borrar_<?php echo $permi->id_permiso?>">Borrar</a></td>
	</tr>
    
    <!-- MODAL BORRA REGISTRO-->
	<div class="modal fade" id="borrar_<?php echo $permi->id_permiso?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
      		<div class="modal-content">
        		<div class="modal-header">
          			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          			<h4 class="modal-title">Borrar Permiso</h4>
        		</div>
                
        		<div class="modal-body">
          			Realmente desea borra el registro <strong><?php echo $permi->permiso?></strong>?
        		</div>
        		<div class="modal-footer">
          			<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          			<button type="button" class="btn btn-danger" onclick="location.href='<?php echo $this->_conf['base_url'] . 'administrador/acl/borrar_permiso/' . $permi->id_permiso?>'">
                    	Borrar registro
                    </button>
        		</div>
      		</div><!-- /.modal-content -->
    	</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
    
    <!-- MODAL EDITAR REGISTRO-->
	<div class="modal fade" id="editar_<?php echo $permi->id_permiso?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
      		<div class="modal-content">
        		<div class="modal-header">
          			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          			<h4 class="modal-title">Editar Permiso <em class="text-info"><?php echo $permi->permiso?></em></h4>
        		</div>
                
        		<div class="modal-body">
                    <form role="form" action="" method="post" name="editar_registro_<?php echo $permi->id_permiso?>">
                    <input type="hidden" name="editar_permiso" value="1" />
                    <input type="hidden" name="editar_permiso_id" value="<?php echo $permi->id_permiso?>" />
                 		<div class="form-group">
                  			<label for="Permiso">Permiso</label>
                      		<input type="text" class="form-control" id="permiso" name="permiso" value="<?php echo $permi->permiso?>">
                     	</div>
                     	<div class="form-group">
                     		<label for="Key">Key</label>
                      		<input type="text" class="form-control" id="key" name="key" value="<?php echo $permi->key?>">
                    	</div>  
                  		<button type="submit" class="btn btn-warning">Editar</button>
                	</form>                    
        		</div>

        		<div class="modal-footer">
          			<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        		</div>
      		</div><!-- /.modal-content -->
    	</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
    
    <?php endforeach?>

</table>
<?php endif ?>

<p>
	<a href="<?php echo $this->_conf['base_url']?>administrador/acl/nuevo_permiso" class="btn btn-primary">
    	<span class="glyphicon glyphicon-plus"></span> Agregar Permiso
    </a>
</p>