<h2>Administracion de Permisos de roles</h2>

<p><strong>Role:</strong> <em class="text-info"><?php echo $this->role->role?></em></p>

<form name="form1" method="post" action="">
    <input type="hidden" name="guardar" value="1" />
    
    <?php if(isset($this->permisos) && count($this->permisos)):?>
    <table class="table table-bordered table-condensed table-striped" style="width: 500px;">
 		<tr>
   			<th>Permiso</th>
        	<th style="text-align: center;">Habilitado</th>
         	<th style="text-align: center;">Denegado</th>
          	<th style="text-align: center;">Ignorar</th>
     	</tr>

        <?php foreach($this->permisos as $valor):?>
        <tr>
         	<td><?php echo $valor['nombre']?></td>
          	<td style="text-align: center;">
                <input type="radio" name="perm_<?php echo $valor['id']?>" value="1" <?php if($valor['valor'] == 1):?>checked="checked"<?php endif?>>
            </td>
           	<td style="text-align: center;">	
                <input type="radio" name="perm_<?php echo $valor['id']?>" value="" <?php if($valor['valor'] == ""):?> checked="checked" <?php endif?>/>
            </td>
          	<td style="text-align: center;">
                <input type="radio" name="perm_<?php echo $valor['id']?>" value="x" <?php if($valor['valor'] === "x"):?> checked="checked" <?php endif?> />
           	</td>
    	</tr>
        <?php endforeach?>
        
        
        
	</table>
    <?php endif?>
    <p><button type="submit" class="btn btn-warning">Guardar</button></p>
</form> 
<hr>
<a href="<?php echo $this->_conf['base_url'] . 'administrador/acl/roles'?>">Atras</a>